export type KitLanguage="en"|"nl"|"fr"|"de"|"es";
export type KitLocale={language:KitLanguage;region:string;timeZone:string};

export const languageNames:Record<KitLanguage,string>={en:"English",nl:"Nederlands",fr:"Français",de:"Deutsch",es:"Español"};

const dictionaries={
 en:{home:"Home",calendar:"Calendar",tasks:"Tasks / To-do",groceries:"Groceries",meals:"Meals",familyHub:"Family Hub",household:"Household",settings:"Settings",personalSettings:"My personal settings",feedback:"Feedback",signOut:"Sign out",notifications:"Household notifications",openFamilyHub:"Open Family Hub",allCaughtUp:"You are all caught up.",searchHome:"Search your home",members:"members",myAccount:"My account",today:"Today",tomorrow:"Tomorrow",week:"Week",month:"Month",agenda:"Agenda",addEvent:"Add event",addTask:"Add task",addItem:"Add item",addMeal:"Add meal",save:"Save",cancel:"Cancel",delete:"Delete",edit:"Edit",search:"Search",send:"Send",title:"Title",description:"Description",starts:"Starts",ends:"Ends",allDay:"All-day",repeat:"Repeat",noEvents:"No events yet",noTasks:"No tasks yet",noMessages:"No messages yet.",householdChat:"Household chat",directMessages:"Direct messages",announcements:"Announcements",activity:"Activity",writeHousehold:"Write to the household…",emoji:"Emoji",stickers:"Stickers",gifs:"GIFs",language:"Language",region:"Region",timeZone:"Time zone",dateTimePreview:"Date & time preview",savePreferences:"Save preferences",pullRefresh:"Pull to refresh",releaseRefresh:"Release to refresh",refreshing:"Refreshing…"},
 nl:{home:"Home",calendar:"Kalender",tasks:"Taken / To-do",groceries:"Boodschappen",meals:"Maaltijden",familyHub:"Familiehub",household:"Huishouden",settings:"Instellingen",personalSettings:"Mijn persoonlijke instellingen",feedback:"Feedback",signOut:"Uitloggen",notifications:"Huishoudmeldingen",openFamilyHub:"Open Familiehub",allCaughtUp:"Je bent helemaal bij.",searchHome:"Doorzoek je thuis",members:"leden",myAccount:"Mijn account",today:"Vandaag",tomorrow:"Morgen",week:"Week",month:"Maand",agenda:"Agenda",addEvent:"Evenement toevoegen",addTask:"Taak toevoegen",addItem:"Item toevoegen",addMeal:"Maaltijd toevoegen",save:"Opslaan",cancel:"Annuleren",delete:"Verwijderen",edit:"Bewerken",search:"Zoeken",send:"Versturen",title:"Titel",description:"Beschrijving",starts:"Begint",ends:"Eindigt",allDay:"Hele dag",repeat:"Herhalen",noEvents:"Nog geen evenementen",noTasks:"Nog geen taken",noMessages:"Nog geen berichten.",householdChat:"Huishoudchat",directMessages:"Directe berichten",announcements:"Aankondigingen",activity:"Activiteit",writeHousehold:"Schrijf naar het huishouden…",emoji:"Emoji",stickers:"Stickers",gifs:"GIFs",language:"Taal",region:"Regio",timeZone:"Tijdzone",dateTimePreview:"Voorbeeld datum en tijd",savePreferences:"Voorkeuren opslaan",pullRefresh:"Trek omlaag om te vernieuwen",releaseRefresh:"Laat los om te vernieuwen",refreshing:"Vernieuwen…"},
 fr:{home:"Accueil",calendar:"Calendrier",tasks:"Tâches / À faire",groceries:"Courses",meals:"Repas",familyHub:"Espace famille",household:"Foyer",settings:"Paramètres",personalSettings:"Mes paramètres personnels",feedback:"Commentaires",signOut:"Se déconnecter",notifications:"Notifications du foyer",openFamilyHub:"Ouvrir l’espace famille",allCaughtUp:"Vous êtes à jour.",searchHome:"Rechercher dans votre foyer",members:"membres",myAccount:"Mon compte",today:"Aujourd’hui",tomorrow:"Demain",week:"Semaine",month:"Mois",agenda:"Agenda",addEvent:"Ajouter un événement",addTask:"Ajouter une tâche",addItem:"Ajouter un article",addMeal:"Ajouter un repas",save:"Enregistrer",cancel:"Annuler",delete:"Supprimer",edit:"Modifier",search:"Rechercher",send:"Envoyer",title:"Titre",description:"Description",starts:"Début",ends:"Fin",allDay:"Toute la journée",repeat:"Répéter",noEvents:"Aucun événement",noTasks:"Aucune tâche",noMessages:"Aucun message.",householdChat:"Discussion du foyer",directMessages:"Messages directs",announcements:"Annonces",activity:"Activité",writeHousehold:"Écrire au foyer…",emoji:"Emoji",stickers:"Stickers",gifs:"GIFs",language:"Langue",region:"Région",timeZone:"Fuseau horaire",dateTimePreview:"Aperçu date et heure",savePreferences:"Enregistrer les préférences",pullRefresh:"Tirez pour actualiser",releaseRefresh:"Relâchez pour actualiser",refreshing:"Actualisation…"},
 de:{home:"Start",calendar:"Kalender",tasks:"Aufgaben / To-do",groceries:"Einkäufe",meals:"Mahlzeiten",familyHub:"Familienbereich",household:"Haushalt",settings:"Einstellungen",personalSettings:"Meine persönlichen Einstellungen",feedback:"Feedback",signOut:"Abmelden",notifications:"Haushaltsbenachrichtigungen",openFamilyHub:"Familienbereich öffnen",allCaughtUp:"Du bist auf dem neuesten Stand.",searchHome:"Zuhause durchsuchen",members:"Mitglieder",myAccount:"Mein Konto",today:"Heute",tomorrow:"Morgen",week:"Woche",month:"Monat",agenda:"Agenda",addEvent:"Termin hinzufügen",addTask:"Aufgabe hinzufügen",addItem:"Artikel hinzufügen",addMeal:"Mahlzeit hinzufügen",save:"Speichern",cancel:"Abbrechen",delete:"Löschen",edit:"Bearbeiten",search:"Suchen",send:"Senden",title:"Titel",description:"Beschreibung",starts:"Beginn",ends:"Ende",allDay:"Ganztägig",repeat:"Wiederholen",noEvents:"Noch keine Termine",noTasks:"Noch keine Aufgaben",noMessages:"Noch keine Nachrichten.",householdChat:"Haushaltschat",directMessages:"Direktnachrichten",announcements:"Ankündigungen",activity:"Aktivität",writeHousehold:"An den Haushalt schreiben…",emoji:"Emoji",stickers:"Sticker",gifs:"GIFs",language:"Sprache",region:"Region",timeZone:"Zeitzone",dateTimePreview:"Datum- und Zeitvorschau",savePreferences:"Einstellungen speichern",pullRefresh:"Zum Aktualisieren ziehen",releaseRefresh:"Zum Aktualisieren loslassen",refreshing:"Wird aktualisiert…"},
 es:{home:"Inicio",calendar:"Calendario",tasks:"Tareas / Pendientes",groceries:"Compras",meals:"Comidas",familyHub:"Espacio familiar",household:"Hogar",settings:"Ajustes",personalSettings:"Mis ajustes personales",feedback:"Comentarios",signOut:"Cerrar sesión",notifications:"Notificaciones del hogar",openFamilyHub:"Abrir espacio familiar",allCaughtUp:"Estás al día.",searchHome:"Buscar en tu hogar",members:"miembros",myAccount:"Mi cuenta",today:"Hoy",tomorrow:"Mañana",week:"Semana",month:"Mes",agenda:"Agenda",addEvent:"Añadir evento",addTask:"Añadir tarea",addItem:"Añadir artículo",addMeal:"Añadir comida",save:"Guardar",cancel:"Cancelar",delete:"Eliminar",edit:"Editar",search:"Buscar",send:"Enviar",title:"Título",description:"Descripción",starts:"Empieza",ends:"Termina",allDay:"Todo el día",repeat:"Repetir",noEvents:"Aún no hay eventos",noTasks:"Aún no hay tareas",noMessages:"Aún no hay mensajes.",householdChat:"Chat del hogar",directMessages:"Mensajes directos",announcements:"Anuncios",activity:"Actividad",writeHousehold:"Escribe al hogar…",emoji:"Emoji",stickers:"Stickers",gifs:"GIFs",language:"Idioma",region:"Región",timeZone:"Zona horaria",dateTimePreview:"Vista previa de fecha y hora",savePreferences:"Guardar preferencias",pullRefresh:"Desliza para actualizar",releaseRefresh:"Suelta para actualizar",refreshing:"Actualizando…"}
} as const;

export type TranslationKey=keyof typeof dictionaries.en;
export function normalizeLanguage(value:string|undefined|null):KitLanguage{return value&&value in dictionaries?value as KitLanguage:"en"}
export function translate(language:KitLanguage,key:TranslationKey){return dictionaries[language][key]??dictionaries.en[key]}
export function localeTag(locale:KitLocale){return locale.region?`${locale.language}-${locale.region.toUpperCase()}`:locale.language}
export function formatDateTime(value:string|Date,locale:KitLocale,options:Intl.DateTimeFormatOptions={dateStyle:"medium",timeStyle:"short"}){return new Intl.DateTimeFormat(localeTag(locale),{...options,timeZone:locale.timeZone||undefined}).format(new Date(value))}
export function formatDate(value:string|Date,locale:KitLocale,options:Intl.DateTimeFormatOptions={dateStyle:"medium"}){return new Intl.DateTimeFormat(localeTag(locale),{...options,timeZone:locale.timeZone||undefined}).format(new Date(value))}
export function formatTime(value:string|Date,locale:KitLocale,options:Intl.DateTimeFormatOptions={timeStyle:"short"}){return new Intl.DateTimeFormat(localeTag(locale),{...options,timeZone:locale.timeZone||undefined}).format(new Date(value))}
export function announceLocale(locale:KitLocale){localStorage.setItem("kit-hub-language",locale.language);localStorage.setItem("kit-hub-region",locale.region);localStorage.setItem("kit-hub-timezone",locale.timeZone);document.documentElement.lang=locale.language;window.dispatchEvent(new CustomEvent("kit-hub-locale-changed",{detail:locale}))}
