import { LogOut, RefreshCw, ShieldCheck, Smartphone, X } from "lucide-react";
import { useEffect, useState } from "react";
import { authClient } from "../lib/auth-client";
import "../account-security.css";

type SessionInfo={id:string;device:string;createdAt:number;updatedAt:number;expiresAt:number};
type Data={sessions:SessionInfo[];note:string};
async function request<T>(url:string,init?:RequestInit){const response=await fetch(url,{credentials:"include",...init,headers:{"content-type":"application/json",...init?.headers}});const body=await response.json().catch(()=>({})) as any;if(!response.ok)throw new Error(body?.error?.message||"Account security could not complete that action.");return body as T}
function when(value:number){if(!value)return "Unknown";const milliseconds=value<10_000_000_000?value*1000:value;return new Date(milliseconds).toLocaleString()}
export function AccountSecurityDock(){const[open,setOpen]=useState(false),[data,setData]=useState<Data|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");async function load(){setBusy(true);setError("");try{setData(await request<Data>("/api/v1/security/sessions"))}catch(e){setError(e instanceof Error?e.message:"Account security could not be loaded.")}finally{setBusy(false)}}useEffect(()=>{const show=()=>{setOpen(true);void load()};window.addEventListener("kit-hub-open-account-security",show);return()=>window.removeEventListener("kit-hub-open-account-security",show)},[]);async function signOutEverywhere(){if(!confirm("Sign out every Kit Hub session, including this device? You will need to sign in again."))return;setBusy(true);setError("");try{await request("/api/v1/security/sign-out-everywhere",{method:"POST",body:"{}"});await authClient.signOut().catch(()=>undefined);window.location.href="/"}catch(e){setError(e instanceof Error?e.message:"Sessions could not be signed out.");setBusy(false)}}return <><button className="account-security-launcher" type="button" onClick={()=>{setOpen(true);void load()}}><ShieldCheck/><span>Security</span></button>{open&&<div className="account-security-backdrop" onMouseDown={()=>setOpen(false)}><section className="account-security-panel" onMouseDown={e=>e.stopPropagation()}><header><div><small>ACCOUNT SECURITY</small><h2>Your signed-in devices</h2><p>Review active Kit Hub sessions and remove access everywhere if something looks wrong.</p></div><button className="icon-button" onClick={()=>setOpen(false)}><X/></button></header>{error&&<p className="module-alert">{error}</p>}<div className="account-security-toolbar"><button className="button button--secondary button--compact" disabled={busy} onClick={()=>void load()}><RefreshCw className={busy?"spin":""}/> Refresh</button><button className="button button--secondary button--compact account-security-danger" disabled={busy} onClick={()=>void signOutEverywhere()}><LogOut/> Sign out everywhere</button></div>{!data?<p>Loading sessions…</p>:<><div className="account-security-sessions">{data.sessions.map(session=><article key={session.id}><Smartphone/><div><strong>{session.device}</strong><small>Last active {when(session.updatedAt)}</small><small>Session expires {when(session.expiresAt)}</small></div></article>)}{!data.sessions.length&&<p>No active sessions were found.</p>}</div><p className="account-security-note"><ShieldCheck/>{data.note}</p></>}</section></div>}</>}
