import { useEffect, useMemo, useState } from "react";
import { BarChart3, CheckCircle2, RefreshCw, Sparkles, UsersRound } from "lucide-react";

type Insight={
  households:number;
  activation:{activated:number;eligible:number;percent:number|null;definition:string};
  retention:{d1:{eligible:number;retained:number;percent:number|null};d7:{eligible:number;retained:number;percent:number|null};d30:{eligible:number;retained:number;percent:number|null}};
  featureAdoption:Array<{eventKey:string;households:number;percent:number}>;
  journey:Array<{key:string;label:string;households:number;percent:number}>;
  privacyNote:string;
};
const labels:Record<string,string>={calendar_view:"Calendar",tasks_view:"Tasks",groceries_view:"Groceries",meals_view:"Meals",family_hub_view:"Family Hub",family_plan_view:"Family Plan",routines_view:"Routines",search_used:"Search",feedback_opened:"Feedback",silvi_opened:"Silvi"};
async function request<T>(url:string){const response=await fetch(url,{credentials:"include"});const body=await response.json().catch(()=>({})) as any;if(!response.ok)throw new Error(body?.error?.message||"Adoption data could not be loaded.");return body as T}
function retention(value:{eligible:number;retained:number;percent:number|null},label:string){return <article><RefreshCw/><strong>{value.percent===null?"—":`${value.percent}%`}</strong><span>{label} retention</span><small>{value.eligible?`${value.retained} of ${value.eligible} eligible households returned`:"Not enough elapsed beta time yet"}</small></article>}
export function AdminAdoptionPanel(){const[data,setData]=useState<Insight|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);async function load(){setBusy(true);setError("");try{setData(await request<Insight>("/api/v1/admin/adoption-insights"))}catch(e){setError(e instanceof Error?e.message:"Adoption data could not be loaded.")}finally{setBusy(false)}}useEffect(()=>{void load()},[]);const max=useMemo(()=>Math.max(1,...(data?.featureAdoption.map(x=>x.percent)??[1])),[data]);return <section className="admin-adoption-shell"><header className="admin-launch-heading"><div><small>ADOPTION & RETENTION</small><h2>Are households actually adopting Kit Hub?</h2><p>Measure meaningful household use, not just sign-ups. These metrics stay aggregate and do not inspect family content.</p></div><button className="admin-secondary" onClick={()=>void load()} disabled={busy}><RefreshCw className={busy?"spin":""}/>{busy?"Refreshing…":"Refresh"}</button></header>{error&&<div className="admin-launch-error">{error}</div>}{data&&<><div className="admin-launch-metrics"><article><Sparkles/><strong>{data.activation.percent===null?"—":`${data.activation.percent}%`}</strong><span>Activated households</span><small>{data.activation.activated} of {data.activation.eligible} eligible · {data.activation.definition}</small></article>{retention(data.retention.d1,"D1")}{retention(data.retention.d7,"D7")}{retention(data.retention.d30,"D30")}</div><div className="admin-launch-grid"><article className="admin-launch-card"><header><UsersRound/><div><small>HOUSEHOLD JOURNEY</small><h3>From setup to repeat use</h3></div></header><div className="admin-journey">{data.journey.map(item=><div key={item.key}><span className={item.percent>=50?"is-strong":""}><CheckCircle2/></span><div><strong>{item.label}</strong><small>{item.households} household{item.households===1?"":"s"}</small></div><b>{item.percent}%</b></div>)}</div></article><article className="admin-launch-card"><header><BarChart3/><div><small>FEATURE ADOPTION</small><h3>Which parts become habits?</h3></div></header><div className="admin-feature-bars">{data.featureAdoption.map(feature=><div key={feature.eventKey}><span><strong>{labels[feature.eventKey]||feature.eventKey}</strong><small>{feature.households} household{feature.households===1?"":"s"} · {feature.percent}% adoption</small></span><i><b style={{width:`${Math.max(5,(feature.percent/max)*100)}%`}}/></i></div>)}</div><p className="admin-launch-privacy">{data.privacyNote}</p></article></div></>}</section>}
