import { CheckCircle2, Circle, RefreshCw, Route, UsersRound } from "lucide-react";
import { useEffect, useState } from "react";
import "../admin-beta-journey.css";

type Tester={email:string;displayName:string|null;status:string;invitedAt:string;activatedAt:string|null;signedIn:boolean;householdReady:boolean;sharedActionDone:boolean;silviTried:boolean;feedbackSubmitted:boolean;welcomeSeen:boolean;completed:number;total:number;percent:number};
type Data={testers:Tester[];summary:{invited:number;activated:number;householdReady:number;firstAction:number;silviTried:number;feedback:number}};
async function request<T>(url:string){const response=await fetch(url,{credentials:"include"});const body=await response.json().catch(()=>({})) as any;if(!response.ok)throw new Error(body?.error?.message||"Tester journey could not be loaded.");return body as T}
const steps=[{key:"signedIn",label:"Signed in"},{key:"householdReady",label:"Household ready"},{key:"sharedActionDone",label:"First shared action"},{key:"silviTried",label:"Tried Silvi"},{key:"feedbackSubmitted",label:"First feedback"}] as const;
export function AdminBetaJourneyPanel(){const[data,setData]=useState<Data|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");async function load(){setBusy(true);setError("");try{setData(await request<Data>("/api/v1/admin/beta-journey"))}catch(e){setError(e instanceof Error?e.message:"Tester journey could not be loaded.")}finally{setBusy(false)}}useEffect(()=>{void load()},[]);return <section className="admin-launch-shell"><header className="admin-launch-heading"><div><small>FIRST-SESSION JOURNEY</small><h2>Are testers actually getting started?</h2><p>Follow each approved tester from sign-in to a real household action, Silvi and first feedback without collecting family content.</p></div><button className="admin-secondary" onClick={()=>void load()} disabled={busy}><RefreshCw className={busy?"spin":""}/>{busy?"Refreshing…":"Refresh"}</button></header>{error&&<div className="admin-launch-error">{error}</div>}{data&&<><div className="admin-launch-metrics"><article><UsersRound/><strong>{data.summary.activated}/{data.summary.invited}</strong><span>Activated</span><small>Approved testers who entered Kit Hub</small></article><article><Route/><strong>{data.summary.householdReady}</strong><span>Household ready</span><small>Created or joined a household</small></article><article><CheckCircle2/><strong>{data.summary.firstAction}</strong><span>First shared action</span><small>Task, grocery item or calendar event</small></article><article><CheckCircle2/><strong>{data.summary.feedback}</strong><span>First feedback</span><small>Submitted through the tester feedback tool</small></article></div><article className="admin-launch-card"><header><Route/><div><small>TESTER PROGRESS</small><h3>Invitation → useful first session</h3></div></header><div className="admin-beta-journeys">{data.testers.length?data.testers.map(t=><div className="admin-beta-journey" key={t.email}><header><div><strong>{t.displayName||t.email}</strong>{t.displayName&&<small>{t.email}</small>}<small>{t.activatedAt?`Activated ${new Date(t.activatedAt).toLocaleDateString()}`:`Invited ${new Date(t.invitedAt).toLocaleDateString()}`}</small></div><b>{t.percent}%</b></header><div className="admin-beta-journey__bar"><i style={{width:`${t.percent}%`}}/></div><div className="admin-beta-journey__steps">{steps.map(step=>{const done=Boolean(t[step.key]);return <span className={done?"is-done":""} key={step.key}>{done?<CheckCircle2/>:<Circle/>}{step.label}</span>})}</div></div>):<p>No beta testers yet.</p>}</div></article></>}</section>}
