import { useEffect } from "react";
import "../content-attachments.css";

type EntityType="note"|"task"|"event"|"meal"|"recipe"|"poll";
type Entity={type:EntityType;id:string;needle:string};
type Attachment={id:string;entityType:string;entityId:string|null;fileName:string;mimeType:string;sizeBytes:number;uploadedByName:string;createdAt:string};
type Everyday={tasks:Array<{id:string;title:string}>;events:Array<{id:string;title:string}>};
type Home={notes:Array<{id:string;body:string}>};
type Meals={plans:Array<{id:string;title:string}>;recipes:Array<{id:string;name:string}>};
type Tools={polls:Array<{id:string;question:string}>;attachments:Attachment[]};

async function json<T>(url:string,init?:RequestInit){const response=await fetch(url,{credentials:"include",...init,headers:{"content-type":"application/json",...init?.headers}});const body=await response.json().catch(()=>null) as T&{error?:{message?:string}};if(!response.ok)throw new Error(body?.error?.message||"That attachment action could not be completed.");return body}
function b64(file:File){return new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result||"").split(",")[1]||"");r.onerror=()=>reject(new Error("The file could not be read."));r.readAsDataURL(file)})}
function clean(value:string){return value.replace(/\s+/g," ").trim().toLowerCase()}

export function AttachmentEnhancer({householdId}:{householdId:string}){
 useEffect(()=>{let dead=false,entities:Entity[]=[],attachments:Attachment[]=[],queued=false;const base=`/api/v1/households/${encodeURIComponent(householdId)}`;
  async function load(){try{const[e,h,m,t]=await Promise.all([json<Everyday>(`${base}/everyday`),json<Home>(`${base}/home`),json<Meals>(`${base}/meals`),json<Tools>(`${base}/family-tools`)]);if(dead)return;entities=[...e.tasks.map(x=>({type:"task" as const,id:x.id,needle:x.title})),...e.events.map(x=>({type:"event" as const,id:x.id,needle:x.title})),...h.notes.map(x=>({type:"note" as const,id:x.id,needle:x.body})),...m.plans.map(x=>({type:"meal" as const,id:x.id,needle:x.title})),...m.recipes.map(x=>({type:"recipe" as const,id:x.id,needle:x.name})),...t.polls.map(x=>({type:"poll" as const,id:x.id,needle:x.question}))];attachments=t.attachments||[];schedule()}catch{/* Main screens already surface their own load errors. */}}
  function candidateFor(element:HTMLElement,types:EntityType[]){const text=clean(element.textContent||"");return entities.find(entity=>types.includes(entity.type)&&entity.needle&&text.includes(clean(entity.needle)))??null}
  function renderFiles(box:HTMLElement,entity:Entity){const list=box.querySelector<HTMLElement>(".kit-attachment-list");if(!list)return;list.innerHTML="";const files=attachments.filter(a=>a.entityType===entity.type&&a.entityId===entity.id);for(const file of files){const row=document.createElement("span");row.className="kit-attachment-chip";const link=document.createElement("a");link.href=`${base}/attachments/${encodeURIComponent(file.id)}?raw=1`;link.target="_blank";link.rel="noreferrer";link.textContent=file.mimeType?.startsWith("image/")?`🖼️ ${file.fileName}`:`📄 ${file.fileName}`;row.appendChild(link);list.appendChild(row)}const count=box.querySelector<HTMLElement>(".kit-attachment-count");if(count)count.textContent=files.length?String(files.length):"";const input=box.querySelector<HTMLInputElement>("input[type=file]");if(input)input.disabled=files.length>=3}
  function mount(element:HTMLElement,entity:Entity,after=false){const key=`${entity.type}:${entity.id}`;if(document.querySelector(`[data-kit-attachment-box="${CSS.escape(key)}"]`))return;const box=document.createElement("span");box.className="kit-attachment-box";box.dataset.kitAttachmentBox=key;const toggle=document.createElement("button");toggle.type="button";toggle.className="kit-attachment-toggle";toggle.innerHTML=`<span aria-hidden="true">📎</span> Files <b class="kit-attachment-count"></b>`;const panel=document.createElement("span");panel.className="kit-attachment-panel";panel.hidden=true;const list=document.createElement("span");list.className="kit-attachment-list";const label=document.createElement("label");label.className="kit-attachment-add";label.innerHTML=`<span>＋ Add photo or file</span>`;const input=document.createElement("input");input.type="file";input.accept="image/png,image/jpeg,image/webp,image/gif,application/pdf,text/plain";input.hidden=true;label.appendChild(input);const note=document.createElement("small");note.textContent="Up to 3 files · 1.5 MB each";panel.append(list,label,note);box.append(toggle,panel);toggle.addEventListener("click",e=>{e.preventDefault();e.stopPropagation();panel.hidden=!panel.hidden});label.addEventListener("click",e=>e.stopPropagation());input.addEventListener("change",async()=>{const file=input.files?.[0];if(!file)return;if(file.size>1572864){note.textContent="That file is larger than 1.5 MB.";input.value="";return}note.textContent="Uploading…";try{const dataBase64=await b64(file);const created=await json<Attachment>(`${base}/attachments`,{method:"POST",body:JSON.stringify({entityType:entity.type,entityId:entity.id,fileName:file.name,mimeType:file.type||"application/octet-stream",dataBase64})});attachments=[created,...attachments];renderFiles(box,entity);note.textContent="Uploaded · visible to your household."}catch(error){note.textContent=error instanceof Error?error.message:"Upload failed."}finally{input.value=""}});if(after)element.insertAdjacentElement("afterend",box);else element.appendChild(box);renderFiles(box,entity)}
  function enhance(){queued=false;const mappings:Array<{selector:string;types:EntityType[];after?:boolean}>=[{selector:".task-row",types:["task"]},{selector:".family-note-list article",types:["note"]},{selector:".calendar-v2-agenda-event",types:["event"]},{selector:".dashboard-meal-card",types:["meal"]},{selector:"button.meal-slot.is-planned",types:["meal"],after:true},{selector:".meal-recipe-list article",types:["recipe"]},{selector:".poll-card",types:["poll"]}];for(const mapping of mappings)for(const element of Array.from(document.querySelectorAll<HTMLElement>(mapping.selector))){if(element.closest("[data-no-attachments]"))continue;const entity=candidateFor(element,mapping.types);if(entity)mount(element,entity,Boolean(mapping.after))}}
  function schedule(){if(queued)return;queued=true;requestAnimationFrame(enhance)}void load();const observer=new MutationObserver(schedule);observer.observe(document.body,{subtree:true,childList:true});return()=>{dead=true;observer.disconnect()}
 },[householdId]);return null
}
