import { useEffect, useRef, useState } from "react";
import { Image, Link, LoaderCircle, RefreshCw, Search, Smile, Sparkles } from "lucide-react";
import { GiphyFetch } from "@giphy/js-fetch-api";
import "../chat-expression.css";
const groups=[{name:"People",items:["😀","😄","😂","🥰","😍","🤗","🥳","😎","🤔","😭","😴","🤭","🫶","👏","🙌","👍","👎","🙏"]},{name:"Family",items:["❤️","🩷","💛","💚","💙","💜","🏡","👨‍👩‍👧‍👦","👶","🧒","🐶","🐱","🐾","🌈","⭐","✨","🎉","🎂"]},{name:"Everyday",items:["☕","🍕","🍝","🍦","🍿","🥐","🍓","🛒","📚","⚽","🎮","🎵","🚗","✈️","🌞","🌧️","🔥","✅"]}];
const stickers=["🏡❤️","YOU GOT THIS! 💪","BIG HUG 🤗","DINNER TIME! 🍽️","LOVE YOU! 💕","YAY! 🎉","GOOD NIGHT 🌙","ON MY WAY 🚗","THANK YOU! 🌼","FAMILY TIME ✨"];
type GifResult={id:string;url:string;previewUrl:string;title:string};
type GifStatus={configured:boolean;available:boolean;provider:string;message?:string};
type GiphyClient=InstanceType<typeof GiphyFetch>;
function sdkError(error:unknown){const message=error instanceof Error?error.message:String(error||"");if(/401|403|unauthor/i.test(message))return"GIPHY rejected the Web SDK key. Check that the deployed key belongs to your Web · JS/React SDK app.";return message||"GIF search is not available yet."}
function toResult(item:any):GifResult|null{const original=item?.images?.original?.url||item?.images?.fixed_width?.url;const preview=item?.images?.fixed_width_small?.url||item?.images?.fixed_width?.url||original;if(!original||!preview)return null;return{id:String(item.id||original),url:String(original),previewUrl:String(preview),title:String(item.title||"GIF")}}
export function ChatExpressionPicker({onInsert,onGif}:{onInsert:(value:string)=>void;onGif:(url:string)=>void}){const[tab,setTab]=useState<"emoji"|"stickers"|"gifs">("emoji"),[query,setQuery]=useState(""),[gifUrl,setGifUrl]=useState(""),[gifQuery,setGifQuery]=useState(""),[results,setResults]=useState<GifResult[]>([]),[searching,setSearching]=useState(false),[checking,setChecking]=useState(false),[gifMessage,setGifMessage]=useState(""),[gifStatus,setGifStatus]=useState<GifStatus|null>(null);const clientRef=useRef<GiphyClient|null>(null);const filtered=groups.map(g=>({...g,items:query?g.items.filter(x=>x.includes(query)):g.items}));
async function connectSdk(){const controller=new AbortController();const timer=window.setTimeout(()=>controller.abort(),8000);try{const response=await fetch("/api/v1/media/gifs/sdk-config",{credentials:"include",cache:"no-store",signal:controller.signal});const body=await response.json().catch(()=>({})) as {apiKey?:string;error?:{message?:string}};if(!response.ok||!body.apiKey)throw new Error(body.error?.message||"GIPHY Web SDK is not configured yet.");const client=new GiphyFetch(body.apiKey);clientRef.current=client;return client}finally{window.clearTimeout(timer)}}
async function refreshGifStatus(){if(checking)return;setChecking(true);setGifMessage("");try{const client=clientRef.current||await connectSdk();await client.trending({limit:1,rating:"g"});setGifStatus({configured:true,available:true,provider:"GIPHY Web SDK",message:"GIPHY Web SDK is ready."})}catch(error){const message=error instanceof DOMException&&error.name==="AbortError"?"Kit Hub could not load the GIPHY SDK configuration. Check the deployed Worker and try again.":sdkError(error);setGifStatus({configured:true,available:false,provider:"GIPHY Web SDK",message});setGifMessage(message);clientRef.current=null}finally{setChecking(false)}}
useEffect(()=>{if(tab!=="gifs"||gifStatus!==null)return;void refreshGifStatus()},[tab,gifStatus]);
async function searchGifs(){const q=gifQuery.trim();if(!q||searching||gifStatus?.available!==true)return;setSearching(true);setGifMessage("");try{const client=clientRef.current||await connectSdk();const response=await client.search(q,{limit:18,offset:0,rating:"g",lang:"en"});const next=(Array.isArray(response.data)?response.data:[]).map(toResult).filter((item):item is GifResult=>Boolean(item));setResults(next);if(!next.length)setGifMessage("No GIFs found. Try another search or paste a link below.")}catch(error){setResults([]);setGifMessage(sdkError(error));setGifStatus({configured:true,available:false,provider:"GIPHY Web SDK",message:sdkError(error)});clientRef.current=null}finally{setSearching(false)}}
function addLink(){const value=gifUrl.trim();if(/^https:\/\/(media\.giphy\.com|i\.giphy\.com|media\.tenor\.com)\//i.test(value)){onGif(value);setGifUrl("");setGifMessage("")}else setGifMessage("Use a direct GIPHY or Tenor media link.")}
const ready=gifStatus?.available===true;
return <div className="chat-expression-picker"><nav><button type="button" className={tab==="emoji"?"active":""} onClick={()=>setTab("emoji")}><Smile/>Emoji</button><button type="button" className={tab==="stickers"?"active":""} onClick={()=>setTab("stickers")}><Sparkles/>Stickers</button><button type="button" className={tab==="gifs"?"active":""} onClick={()=>setTab("gifs")}><Image/>GIFs</button></nav>{tab==="emoji"&&<div className="chat-expression-emoji"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find an emoji"/></label>{filtered.map(group=><section key={group.name}><strong>{group.name}</strong><div>{group.items.map(emoji=><button type="button" key={emoji} onClick={()=>onInsert(emoji)}>{emoji}</button>)}</div></section>)}</div>}{tab==="stickers"&&<div className="chat-expression-stickers"><p>Kit Hub starter pack</p>{stickers.map(sticker=><button type="button" key={sticker} onClick={()=>onInsert(`\n${sticker}\n`)}>{sticker}</button>)}</div>}{tab==="gifs"&&<div className="chat-expression-gif"><div className="chat-expression-gif-search"><Search/><input value={gifQuery} disabled={!ready} onChange={e=>setGifQuery(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();void searchGifs()}}} placeholder={gifStatus===null||checking?"Connecting GIPHY Web SDK…":ready?"Search GIFs — hug, happy, dinner…":"GIF search is not ready"}/><button type="button" onClick={()=>void searchGifs()} disabled={searching||!gifQuery.trim()||!ready}>{searching?<LoaderCircle className="spin"/>:"Search"}</button></div>{ready&&<small className="chat-expression-gif-provider">GIPHY Web SDK connected · Powered by GIPHY</small>}{gifStatus&&!ready&&<div className="chat-expression-gif-status"><p>{gifMessage||gifStatus.message}</p><button type="button" disabled={checking} onClick={()=>void refreshGifStatus()}>{checking?<LoaderCircle className="spin"/>:<RefreshCw/>}{checking?"Checking…":"Check again"}</button></div>}{results.length>0&&<div className="chat-expression-gif-results">{results.map(item=><button type="button" key={item.id} title={item.title} onClick={()=>onGif(item.url)}><img src={item.previewUrl} alt={item.title||"GIF"} loading="lazy"/></button>)}</div>}{ready&&gifMessage&&<p>{gifMessage}</p>}<details open={!ready}><summary><Link/> Have a GIF link instead?</summary><div className="chat-expression-gif-link"><input value={gifUrl} onChange={e=>setGifUrl(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();addLink()}}} placeholder="https://media.giphy.com/…"/><button type="button" onClick={addLink}>Add link</button></div></details></div>}</div>}
