import { useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";
import { AlertTriangle, ArrowRight, CalendarDays, ChefHat, Repeat2, UsersRound } from "lucide-react";
import "../family-coordination-hub.css";

type Context={summary:{overdueRoutines:number};tasks:Array<{assigneeUserId:string|null}>;upcomingEvents:Array<{startsAt:string;endsAt:string|null;allDay:number|boolean}>;meals:Array<{mealDate:string;mealType:string;cookUserId:string|null}>;routines:Array<{assigneeUserId:string|null;overdue:number|boolean}>};
type Preferences={overdue:boolean;unassigned:boolean;conflicts:boolean;mealGaps:boolean;homeWidget:boolean};
const defaults:Preferences={overdue:true,unassigned:true,conflicts:true,mealGaps:true,homeWidget:true};
const prefKey=(householdId:string)=>`kit-hub-coordination-prefs:${householdId}`;
function readPrefs(householdId:string):Preferences{try{return{...defaults,...JSON.parse(localStorage.getItem(prefKey(householdId))||"{}")}}catch{return defaults}}
function dayKey(value:Date){return `${value.getFullYear()}-${String(value.getMonth()+1).padStart(2,"0")}-${String(value.getDate()).padStart(2,"0")}`}
async function getContext(householdId:string){const response=await fetch(`/api/v1/households/${encodeURIComponent(householdId)}/silvi/context`,{credentials:"include",cache:"no-store"});if(!response.ok)throw new Error("Family coordination could not be loaded.");return response.json() as Promise<Context>}

export function CoordinationAttentionHome({householdId}:{householdId:string}){
 const[target,setTarget]=useState<HTMLElement|null>(null),[context,setContext]=useState<Context|null>(null),[prefs,setPrefs]=useState<Preferences>(()=>readPrefs(householdId));
 useEffect(()=>{const locate=()=>setTarget(document.querySelector<HTMLElement>(".dashboard-widget-grid"));locate();const observer=new MutationObserver(locate);observer.observe(document.body,{childList:true,subtree:true});return()=>observer.disconnect()},[]);
 useEffect(()=>{setPrefs(readPrefs(householdId));const changed=(event:Event)=>{const detail=(event as CustomEvent<{householdId?:string;preferences?:Preferences}>).detail;if(detail?.householdId===householdId&&detail.preferences)setPrefs(detail.preferences)};window.addEventListener("kit-hub-coordination-preferences",changed);return()=>window.removeEventListener("kit-hub-coordination-preferences",changed)},[householdId]);
 useEffect(()=>{let dead=false;const load=()=>void getContext(householdId).then(data=>{if(!dead)setContext(data)}).catch(()=>{});load();const timer=window.setInterval(load,60000);const updated=()=>load();window.addEventListener("kit-hub-coordination-updated",updated);return()=>{dead=true;window.clearInterval(timer);window.removeEventListener("kit-hub-coordination-updated",updated)}},[householdId]);
 const issues=useMemo(()=>{if(!context)return{overdue:0,unassigned:0,conflicts:0,mealGaps:0};const unassigned=context.tasks.filter(x=>!x.assigneeUserId).length+context.routines.filter(x=>!x.assigneeUserId).length+context.meals.filter(x=>x.mealType==="dinner"&&!x.cookUserId).length;const timed=context.upcomingEvents.filter(e=>!e.allDay&&e.endsAt),conflicts=new Set<string>();for(let i=0;i<timed.length;i++){const a=timed[i];if(!a)continue;for(let j=i+1;j<timed.length;j++){const b=timed[j];if(!b)continue;if(Date.parse(a.startsAt)<Date.parse(b.endsAt||b.startsAt)&&Date.parse(b.startsAt)<Date.parse(a.endsAt||a.startsAt))conflicts.add(`${i}:${j}`)}}const planned=new Set(context.meals.filter(m=>m.mealType==="dinner").map(m=>m.mealDate));let mealGaps=0;for(let offset=0;offset<7;offset++){const d=new Date();d.setDate(d.getDate()+offset);if(!planned.has(dayKey(d)))mealGaps++}return{overdue:context.summary.overdueRoutines,unassigned,conflicts:conflicts.size,mealGaps}},[context]);
 if(!target||!prefs.homeWidget)return null;const visible=[prefs.overdue&&issues.overdue?{key:"overdue",label:"overdue",value:issues.overdue,Icon:Repeat2}:null,prefs.unassigned&&issues.unassigned?{key:"unassigned",label:"unassigned",value:issues.unassigned,Icon:UsersRound}:null,prefs.conflicts&&issues.conflicts?{key:"conflicts",label:"conflicts",value:issues.conflicts,Icon:CalendarDays}:null,prefs.mealGaps&&issues.mealGaps?{key:"meals",label:"dinner gaps",value:issues.mealGaps,Icon:ChefHat}:null].filter(Boolean) as Array<{key:string;label:string;value:number;Icon:typeof AlertTriangle}>;return createPortal(<section className="dashboard-card dashboard-widget dashboard-widget--medium dashboard-widget-height--normal coordination-home-widget"><div className="dashboard-widget__content"><header><div><small>TODAY NEEDS ATTENTION</small><h2>{visible.length?"A few things to coordinate":"Family plan looks clear"}</h2></div><AlertTriangle/></header>{visible.length?<div className="coordination-home-issues">{visible.map(({key,label,value,Icon})=><span key={key}><Icon/><strong>{value}</strong><small>{label}</small></span>)}</div>:<p>No overdue routines, unassigned work, dinner gaps or schedule conflicts are currently surfaced.</p>}<button type="button" onClick={()=>window.dispatchEvent(new Event("kit-hub-open-family-coordination"))}>Open Family Plan <ArrowRight/></button></div></section>,target)
}
