import { useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";
import { AlertTriangle, ArrowRight, CalendarDays, ChefHat, CheckSquare2, Clock3, MapPin, RefreshCw, Repeat2, Scale, Sparkles, UserRound, UsersRound, X } from "lucide-react";
import "../family-coordination-hub.css";

type Context={currentUserId:string;summary:{openTasks:number;myOpenTasks:number;upcomingEvents:number;plannedMeals:number;activeRoutines:number;myRoutines:number;overdueRoutines:number};tasks:Array<{id:string;title:string;dueAt:string|null;priority:string;assigneeUserId:string|null;assigneeName:string|null}>;upcomingEvents:Array<{id:string;title:string;startsAt:string;endsAt:string|null;allDay:number}>;meals:Array<{id:string;mealDate:string;mealType:string;title:string;cookUserId:string|null;cookName:string|null}>;routines:Array<{id:string;title:string;nextDueAt:string|null;assigneeUserId:string|null;assigneeName:string|null;overdue:number}>};
type Insights={workload:Array<{userId:string;name:string;open:number;openTasks:number;openRoutines:number;overdue:number;completed30?:number}>};
type Presence={presence:Array<{userId:string;name:string;status:string|null;statusExpiresAt:string|null;location:{label?:string|null;latitude:number;longitude:number;accuracy:string;expiresAt:string}|null;own:boolean}>};
type WindowMode="today"|"week";
type FlowKind="event"|"task"|"routine"|"meal";
type FlowRow={id:string;when:number;kind:FlowKind;title:string;meta:string;urgent:boolean};

async function json<T>(url:string){const response=await fetch(url,{credentials:"include"});const body=await response.json().catch(()=>({})) as any;if(!response.ok)throw new Error(body?.error?.message||"Family coordination could not be loaded.");return body as T}
function dayKey(value:Date){return `${value.getFullYear()}-${String(value.getMonth()+1).padStart(2,"0")}-${String(value.getDate()).padStart(2,"0")}`}
function isSameDay(a:number,b:number){const left=new Date(a),right=new Date(b);return left.getFullYear()===right.getFullYear()&&left.getMonth()===right.getMonth()&&left.getDate()===right.getDate()}

export function FamilyCoordinationHub({householdId}:{householdId:string}){
 const[sidebarNav,setSidebarNav]=useState<HTMLElement|null>(null),[open,setOpen]=useState(false),[context,setContext]=useState<Context|null>(null),[insights,setInsights]=useState<Insights|null>(null),[presence,setPresence]=useState<Presence|null>(null),[mode,setMode]=useState<WindowMode>("today"),[busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>{const locate=()=>setSidebarNav(document.querySelector<HTMLElement>(".sidebar-nav"));locate();const observer=new MutationObserver(locate);observer.observe(document.body,{childList:true,subtree:true});return()=>observer.disconnect()},[]);
 useEffect(()=>{const handler=()=>setOpen(true);window.addEventListener("kit-hub-open-family-coordination",handler);return()=>window.removeEventListener("kit-hub-open-family-coordination",handler)},[]);
 useEffect(()=>{if(!open)return;void load();const timer=window.setInterval(()=>void load(false),60000);return()=>window.clearInterval(timer)},[open,householdId]);
 async function load(showBusy=true){if(showBusy)setBusy(true);setError("");try{const[c,i,p]=await Promise.all([json<Context>(`/api/v1/households/${encodeURIComponent(householdId)}/silvi/context`),json<Insights>(`/api/v1/households/${encodeURIComponent(householdId)}/silvi/insights`),json<Presence>(`/api/v1/households/${encodeURIComponent(householdId)}/presence`).catch(()=>({presence:[]} as Presence))]);setContext(c);setInsights(i);setPresence(p)}catch(e){setError(e instanceof Error?e.message:"Family coordination could not be loaded.")}finally{if(showBusy)setBusy(false)}}
 const rows=useMemo(()=>{if(!context)return[];const now=Date.now(),today=dayKey(new Date()),end=now+7*86400000;const items:FlowRow[]=[];for(const event of context.upcomingEvents){const when=Date.parse(event.startsAt);if((mode==="today"&&isSameDay(when,now))||(mode==="week"&&when>=new Date(today).getTime()&&when<=end))items.push({id:event.id,when,kind:"event",title:event.title,meta:event.allDay?"All day":new Date(event.startsAt).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}),urgent:false})}for(const task of context.tasks){if(!task.dueAt)continue;const when=Date.parse(task.dueAt),overdue=when<now;if((mode==="today"&&(isSameDay(when,now)||overdue))||(mode==="week"&&when<=end))items.push({id:task.id,when,kind:"task",title:task.title,meta:task.assigneeName||"Unassigned",urgent:overdue||task.priority==="high"||!task.assigneeUserId})}for(const routine of context.routines){if(!routine.nextDueAt)continue;const when=Date.parse(routine.nextDueAt);if((mode==="today"&&(isSameDay(when,now)||Boolean(routine.overdue)))||(mode==="week"&&when<=end))items.push({id:routine.id,when,kind:"routine",title:routine.title,meta:routine.assigneeName||"Unassigned",urgent:Boolean(routine.overdue)||!routine.assigneeUserId})}for(const meal of context.meals){if(meal.mealType!=="dinner")continue;const when=Date.parse(`${meal.mealDate}T18:00:00`);if((mode==="today"&&meal.mealDate===today)||(mode==="week"&&when>=new Date(today).getTime()&&when<=end))items.push({id:meal.id,when,kind:"meal",title:meal.title,meta:meal.cookName?`Cook: ${meal.cookName}`:"Cook unassigned",urgent:!meal.cookUserId})}return items.sort((a,b)=>Number(b.urgent)-Number(a.urgent)||a.when-b.when)},[context,mode]);
 const conflicts=useMemo(()=>{if(!context)return[] as Array<{left:string;right:string;startsAt:string}>;const timed=context.upcomingEvents.filter(event=>!event.allDay&&event.endsAt).slice(0,40),found:Array<{left:string;right:string;startsAt:string}>=[];for(let i=0;i<timed.length;i++){const a=timed[i];if(!a)continue;const aStart=Date.parse(a.startsAt),aEnd=Date.parse(a.endsAt||a.startsAt);for(let j=i+1;j<timed.length;j++){const b=timed[j];if(!b)continue;const bStart=Date.parse(b.startsAt),bEnd=Date.parse(b.endsAt||b.startsAt);if(aStart<bEnd&&bStart<aEnd)found.push({left:a.title,right:b.title,startsAt:a.startsAt})}}return found.slice(0,6)},[context]);
 const unassigned=useMemo(()=>{if(!context)return[] as Array<{kind:FlowKind;id:string;title:string}>;return [...context.tasks.filter(item=>!item.assigneeUserId).map(item=>({kind:"task" as const,id:item.id,title:item.title})),...context.routines.filter(item=>!item.assigneeUserId).map(item=>({kind:"routine" as const,id:item.id,title:item.title})),...context.meals.filter(item=>item.mealType==="dinner"&&!item.cookUserId).map(item=>({kind:"meal" as const,id:item.id,title:item.title}))].slice(0,8)},[context]);
 const heaviest=useMemo(()=>[...(insights?.workload??[])].sort((a,b)=>b.open-a.open)[0],[insights]);
 const sharedNow=useMemo(()=>presence?.presence.filter(item=>!item.own&&(item.status||item.location))??[],[presence]);
 const mine=insights?.workload.find(item=>item.userId===context?.currentUserId);
 const maxOpen=Math.max(1,...(insights?.workload.map(item=>item.open)??[1]));
 const askSilvi=(prompt:string)=>{setOpen(false);window.setTimeout(()=>window.dispatchEvent(new CustomEvent("kit-hub-ask-silvi",{detail:{prompt,autoSubmit:true}})),0)};
 const openRoutines=()=>{setOpen(false);window.setTimeout(()=>document.querySelector<HTMLButtonElement>(".routines-launcher")?.click(),0)};
 const openLegacyPlan=()=>{setOpen(false);window.setTimeout(()=>window.dispatchEvent(new Event("kit-hub-open-coordination")),0)};
 function clickNav(term:string){const button=[...document.querySelectorAll<HTMLButtonElement>(".sidebar-nav button")].find(item=>item.textContent?.toLowerCase().includes(term));button?.click()}
 function activate(kind:FlowKind,id:string){setOpen(false);window.setTimeout(()=>{if(kind==="event"){window.dispatchEvent(new CustomEvent("kit-hub-open-calendar-event",{detail:{eventId:id}}));return}if(kind==="routine"){document.querySelector<HTMLButtonElement>(".routines-launcher")?.click();return}if(kind==="task"){clickNav("task");return}if(kind==="meal")clickNav("meal")},0)}
 const launchButton=<button type="button" className="family-coordination-launch" onClick={()=>setOpen(true)}><Scale/><span>Family plan</span></button>;
 const needsAttention=Boolean(context&&(context.summary.overdueRoutines>0||heaviest&&heaviest.open>=4||conflicts.length||unassigned.length));
 return <>{sidebarNav?createPortal(launchButton,sidebarNav):null}{open&&createPortal(<div className="family-coordination-backdrop" onMouseDown={()=>setOpen(false)}><main className="family-coordination-page" role="dialog" aria-modal="true" aria-label="Family coordination" onMouseDown={event=>event.stopPropagation()}>
   <header className="family-coordination-hero"><div><small>FAMILY COORDINATION</small><h1>What does the family need today?</h1><p>Events, tasks, meals, routines and voluntary presence sharing in one practical view. This is for coordination, not scoring people.</p></div><button className="icon-button" onClick={()=>setOpen(false)} aria-label="Close family coordination"><X/></button></header>
   {error&&<p className="module-alert">{error}</p>}
   {context&&<>
    <section className="family-coordination-summary"><article><CheckSquare2/><strong>{context.summary.openTasks}</strong><span>Open tasks</span><small>{context.summary.myOpenTasks} assigned to you</small></article><article><CalendarDays/><strong>{context.summary.upcomingEvents}</strong><span>Upcoming events</span><small>Household calendar</small></article><article><ChefHat/><strong>{context.summary.plannedMeals}</strong><span>Meals planned</span><small>Dinner coordination</small></article><article className={context.summary.overdueRoutines?"has-alert":""}><Repeat2/><strong>{context.summary.overdueRoutines}</strong><span>Overdue routines</span><small>{context.summary.activeRoutines} active routines</small></article></section>
    {needsAttention&&<section className="family-coordination-attention"><AlertTriangle/><div><strong>Needs attention</strong><p>{context.summary.overdueRoutines?`${context.summary.overdueRoutines} overdue routine${context.summary.overdueRoutines===1?". ":"s. "}`:""}{conflicts.length?`${conflicts.length} possible schedule conflict${conflicts.length===1?". ":"s. "}`:""}{unassigned.length?`${unassigned.length} unassigned item${unassigned.length===1?". ":"s. "}`:""}{heaviest&&heaviest.open>=4?`${heaviest.name} currently has ${heaviest.open} open responsibilities.`:""}</p><button onClick={()=>askSilvi("Review the household coordination picture. Focus on overdue routines, urgent tasks, schedule conflicts, unassigned meals and workload imbalance. Suggest practical changes, but require confirmation before changing anything.")}><Sparkles/>Ask Silvi to help balance this</button></div></section>}
    {(conflicts.length>0||unassigned.length>0)&&<section className="family-coordination-issues"><article className="family-coordination-card"><header><div><small>POSSIBLE CONFLICTS</small><h2>Schedule overlaps</h2></div><CalendarDays/></header>{conflicts.length?<div className="family-coordination-issue-list">{conflicts.map((item,index)=><div key={`${item.left}-${item.right}-${index}`}><strong>{item.left}</strong><span>overlaps with</span><strong>{item.right}</strong><small>{new Date(item.startsAt).toLocaleString()}</small></div>)}</div>:<p>No overlapping timed events detected.</p>}</article><article className="family-coordination-card"><header><div><small>UNASSIGNED</small><h2>Still needs an owner</h2></div><UsersRound/></header>{unassigned.length?<div className="family-coordination-unassigned">{unassigned.map(item=><button key={`${item.kind}-${item.id}`} onClick={()=>activate(item.kind,item.id)}><span className={`is-${item.kind}`}>{item.kind}</span><strong>{item.title}</strong><ArrowRight/></button>)}</div>:<p>Everything currently has an owner.</p>}</article></section>}
    <section className="family-coordination-main-grid"><article className="family-coordination-card family-coordination-agenda"><header><div><small>HOUSEHOLD FLOW</small><h2>{mode==="today"?"Today":"Next 7 days"}</h2></div><div className="family-coordination-window"><button className={mode==="today"?"is-active":""} onClick={()=>setMode("today")}>Today</button><button className={mode==="week"?"is-active":""} onClick={()=>setMode("week")}>7 days</button></div></header>{rows.length?<div className="family-coordination-timeline">{rows.map(row=><button type="button" key={`${row.kind}-${row.id}-${row.when}`} className={row.urgent?"is-urgent":""} onClick={()=>activate(row.kind,row.id)}><time>{mode==="today"?new Date(row.when).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}):new Date(row.when).toLocaleDateString([],{weekday:"short",day:"numeric",month:"short"})}</time><span className={`is-${row.kind}`}>{row.kind}</span><strong>{row.title}</strong><small>{row.meta}</small><ArrowRight className="family-coordination-row-arrow"/></button>)}</div>:<div className="family-coordination-empty"><Clock3/><strong>Nothing needs coordinating here.</strong><span>{mode==="today"?"Today is looking clear.":"No dated household items are recorded for the next seven days."}</span></div>}</article>
      <aside className="family-coordination-side"><article className="family-coordination-card"><header><div><small>YOUR LOAD</small><h2>Your responsibilities</h2></div><UserRound/></header><div className="family-coordination-personal"><span><b>{context.summary.myOpenTasks}</b> tasks</span><span><b>{context.summary.myRoutines}</b> routines</span><span><b>{mine?.overdue??0}</b> overdue</span></div><p>Visible ownership helps the household coordinate before something gets forgotten.</p></article>
      <article className="family-coordination-card"><header><div><small>SHARED NOW</small><h2>Family status</h2></div><MapPin/></header>{sharedNow.length?<div className="family-coordination-presence">{sharedNow.map(item=><div key={item.userId}><strong>{item.name}</strong>{item.status&&<span>{item.status}</span>}{item.location&&<small>{item.location.label||`${item.location.accuracy==="approximate"?"Near":"At"} shared location`}</small>}</div>)}</div>:<p>No one is currently sharing a status or location with you.</p>}</article></aside>
    </section>
    <section className="family-coordination-card"><header><div><small>HOUSEHOLD LOAD</small><h2>Who owns what right now?</h2></div><Scale/></header><div className="family-coordination-workload">{(insights?.workload??[]).map(person=><div key={person.userId}><span><strong>{person.name}</strong><small>{person.openTasks} tasks · {person.openRoutines} routines{person.overdue?` · ${person.overdue} overdue`:""}</small></span><i><b style={{width:`${Math.max(7,(person.open/maxOpen)*100)}%`}}/></i><em>{person.open}</em></div>)}</div><p className="family-coordination-note">This visual is deliberately descriptive rather than competitive. Different responsibilities take different amounts of time and effort.</p></section>
    <section className="family-coordination-actions"><button className="button button--primary" onClick={()=>askSilvi("Give me a concise household plan for today and the next seven days. Highlight urgent tasks, events, routines, meal gaps, ownership and conflicts. Suggest sensible next actions but require confirmation before changing anything.")}><Sparkles/>Plan with Silvi</button><button className="button button--secondary" onClick={openRoutines}><Repeat2/>Routines & chores</button><button className="button button--secondary" onClick={openLegacyPlan}><UsersRound/>Detailed household plan</button><button className="button button--secondary" disabled={busy} onClick={()=>void load()}><RefreshCw/>Refresh</button></section>
   </>}
   {!context&&!error&&<div className="family-coordination-loading">{busy?"Building the family plan…":"Opening family coordination…"}</div>}
  </main></div>,document.body)}</>;
}
