import { useEffect, useState } from "react";
import { Bell, Languages, Paperclip, Vote, X } from "lucide-react";

type Tools={notifications:Array<{id:string;title:string;body?:string;direct:boolean;readAt?:string;createdAt:string}>;polls:Array<{id:string;question:string;options:Array<{id:string;label:string;votes:number;votedByMe:boolean}>}>;attachments:Array<{id:string;fileName:string;sizeBytes:number;uploadedByName:string}>;locale:{language:string;region:string;timeZone:string}};
async function loadTools(householdId:string){const response=await fetch(`/api/v1/households/${householdId}/family-tools`);if(!response.ok)throw new Error("Family tools could not be loaded.");return response.json() as Promise<Tools>}

export function FamilyToolsDock({householdId}:{householdId:string}){
 const [open,setOpen]=useState(false);const [tab,setTab]=useState("notifications");const [data,setData]=useState<Tools|null>(null);const [error,setError]=useState("");
 useEffect(()=>{void loadTools(householdId).then(setData).catch(e=>setError(e instanceof Error?e.message:"Family tools could not be loaded."))},[householdId]);
 const unread=data?.notifications.filter(item=>!item.readAt).length??0;
 return <><button className="family-tools-launcher" onClick={()=>setOpen(true)} aria-label="Open family tools"><Bell/>{unread>0&&<b>{unread>9?"9+":unread}</b>}</button>{open&&<div className="family-tools-backdrop" onMouseDown={()=>setOpen(false)}><section className="family-tools" onMouseDown={event=>event.stopPropagation()}><header><div><small>FAMILY TOOLS</small><h2>Shared household tools</h2></div><button className="icon-button" onClick={()=>setOpen(false)}><X/></button></header><nav><button className={tab==="notifications"?"is-active":""} onClick={()=>setTab("notifications")}><Bell/>Notifications</button><button className={tab==="polls"?"is-active":""} onClick={()=>setTab("polls")}><Vote/>Polls</button><button className={tab==="files"?"is-active":""} onClick={()=>setTab("files")}><Paperclip/>Files & photos</button><button className={tab==="locale"?"is-active":""} onClick={()=>setTab("locale")}><Languages/>Language</button></nav>{error&&<p className="module-alert">{error}</p>}<div className="family-tools__body">{!data?<p>Loading…</p>:tab==="notifications"?<NotificationPanel data={data}/>:tab==="polls"?<PollPanel data={data}/>:tab==="files"?<FilePanel data={data}/>:<LocalePanel data={data}/>}</div></section></div>}</>;
}
function NotificationPanel({data}:{data:Tools}){return <><h3>Relevant notifications</h3><p>Assignments and @mentions are direct. General household activity follows your notification preferences.</p><div className="family-tools-list">{data.notifications.map(item=><article key={item.id} className={item.direct?"is-direct":""}><Bell/><div><strong>{item.title}</strong>{item.body&&<p>{item.body}</p>}<small>{item.direct?"Direct · ":""}{new Date(item.createdAt).toLocaleString()}</small></div></article>)}{!data.notifications.length&&<p>You are all caught up.</p>}</div></>}
function PollPanel({data}:{data:Tools}){return <><h3>Household polls</h3><p>Create and vote through the family-tools API. The first release keeps poll results compact and household-wide.</p><div className="family-tools-list">{data.polls.map(poll=><article key={poll.id}><Vote/><div><strong>{poll.question}</strong><div className="poll-options">{poll.options.map(option=><span key={option.id}>{option.label} <b>{option.votes}</b></span>)}</div></div></article>)}{!data.polls.length&&<p>No polls yet.</p>}</div></>}
function FilePanel({data}:{data:Tools}){return <><h3>Attachments & photos</h3><p>Household files are ready for notes, meals, recipes, messages, tasks, events and polls.</p><div className="family-tools-list">{data.attachments.map(file=><article key={file.id}><Paperclip/><div><strong>{file.fileName}</strong><small>{file.uploadedByName} · {Math.ceil(file.sizeBytes/1024)} KB</small></div></article>)}{!data.attachments.length&&<p>No shared files yet.</p>}</div></>}
function LocalePanel({data}:{data:Tools}){return <><h3>Language & region</h3><p>Locale is saved per user, so household members can use different languages and regional settings.</p><dl className="locale-summary"><div><dt>Language</dt><dd>{data.locale.language}</dd></div><div><dt>Region</dt><dd>{data.locale.region}</dd></div><div><dt>Time zone</dt><dd>{data.locale.timeZone}</dd></div></dl></>}
