import { useEffect, useState, type FormEvent } from "react";
import { Bug, Camera, CheckCircle2, Lightbulb, MessageSquarePlus, X } from "lucide-react";

type Shot={fileName:string;mimeType:string;dataBase64:string};
async function toShot(file:File):Promise<Shot>{return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve({fileName:file.name,mimeType:file.type,dataBase64:String(r.result||"").split(",")[1]||""});r.onerror=()=>reject(new Error("Screenshot could not be read."));r.readAsDataURL(file)})}
export function FeedbackDock({householdId}:{householdId:string}){
 const [open,setOpen]=useState(false),[kind,setKind]=useState<"issue"|"suggestion">("issue"),[title,setTitle]=useState(""),[description,setDescription]=useState(""),[details,setDetails]=useState(""),[errorText,setErrorText]=useState(""),[files,setFiles]=useState<File[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{const show=()=>setOpen(true);window.addEventListener("kit-hub-open-feedback",show);return()=>window.removeEventListener("kit-hub-open-feedback",show)},[]);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");try{const screenshots=await Promise.all(files.slice(0,3).map(toShot));const response=await fetch(`/api/v1/households/${encodeURIComponent(householdId)}/feedback`,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({kind,title,description,details,errorText:kind==="issue"?errorText:null,pageUrl:location.href,userAgent:navigator.userAgent,screenshots})});if(!response.ok)throw new Error("Feedback could not be sent.");setTitle("");setDescription("");setDetails("");setErrorText("");setFiles([]);setMessage("Thanks — your feedback is now in the Kit Hub testing board.")}catch(e){setMessage(e instanceof Error?e.message:"Feedback could not be sent.")}finally{setBusy(false)}}
 return <><button className="feedback-launcher" onClick={()=>setOpen(true)}><MessageSquarePlus/><span>Feedback</span></button>{open&&<div className="feedback-backdrop" onMouseDown={()=>setOpen(false)}><section className="feedback-panel" onMouseDown={e=>e.stopPropagation()}><header><div><small>HELP SHAPE KIT HUB</small><h2>Tester feedback</h2><p>Report anything across Kit Hub that is broken, confusing, missing or could simply be better.</p></div><button className="icon-button" onClick={()=>setOpen(false)}><X/></button></header>{message&&<div className="feedback-message"><CheckCircle2/>{message}</div>}<div className="feedback-kind"><button className={kind==="issue"?"active":""} onClick={()=>setKind("issue")}><Bug/><strong>Something isn’t working</strong><small>Bug, error or unexpected behaviour</small></button><button className={kind==="suggestion"?"active":""} onClick={()=>setKind("suggestion")}><Lightbulb/><strong>Suggestion / improvement</strong><small>Add, change, improve or remove something</small></button></div><form onSubmit={e=>void submit(e)}><label>Title<input required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)} placeholder={kind==="issue"?"What went wrong?":"What could be better?"}/></label><label>{kind==="issue"?"What happened?":"Describe your idea"}<textarea required rows={5} maxLength={3000} value={description} onChange={e=>setDescription(e.target.value)} placeholder={kind==="issue"?"Tell us what you were doing and what happened.":"Tell us what you would add, change, improve or remove."}/></label><label>{kind==="issue"?"What did you expect to happen?":"How would you improve it?"}<textarea rows={4} maxLength={3000} value={details} onChange={e=>setDetails(e.target.value)}/></label>{kind==="issue"&&<label>Error text <small>Optional — paste an error message here</small><textarea rows={3} maxLength={4000} value={errorText} onChange={e=>setErrorText(e.target.value)}/></label>}<label className="feedback-upload"><Camera/><span><strong>Add screenshots</strong><small>{files.length?`${files.length} selected`:`Up to 3 screenshots · PNG, JPG or WebP`}</small></span><input type="file" multiple accept="image/png,image/jpeg,image/webp" onChange={e=>setFiles(Array.from(e.target.files||[]).slice(0,3))}/></label><small className="feedback-context">Kit Hub automatically includes the page, browser/device information and submission time so you do not have to type technical details.</small><button className="button button--primary" disabled={busy}>{busy?"Sending…":"Send to Kit Hub team"}</button></form></section></div>}</>;
}
