import { useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";
import { CalendarPlus, Check, CheckCircle2, ListPlus, Sparkles, UsersRound, Utensils, X } from "lucide-react";
import { api } from "../lib/api";
import "../first-week-guide.css";

type State={members:number;events:number;tasks:number;meals:number;silvi:boolean};
type ActivationEvent="activation_family_invited"|"activation_first_event"|"activation_first_task"|"activation_first_meal"|"activation_silvi_tried"|"activation_household";

export function FirstWeekGuide({householdId}:{householdId:string}){
 const[host,setHost]=useState<HTMLElement|null>(null),[state,setState]=useState<State|null>(null),[hidden,setHidden]=useState(()=>localStorage.getItem(`kit-hub-first-week-hidden:${householdId}`)==="1");
 useEffect(()=>{const locate=()=>setHost(document.querySelector<HTMLElement>(".dashboard-widget-grid"));locate();const observer=new MutationObserver(locate);observer.observe(document.body,{childList:true,subtree:true});return()=>observer.disconnect()},[]);
 useEffect(()=>{let dead=false;async function load(){try{const[core,meals]=await Promise.all([api.everydayCore(householdId),api.meals(householdId)]);if(dead)return;setState({members:core.members.length,events:core.events.length,tasks:core.tasks.length,meals:meals.plans.length,silvi:localStorage.getItem(`kit-hub-silvi-tried:${householdId}`)==="1"})}catch{}}void load();const changed=(event:Event)=>{const detail=(event as CustomEvent<{householdId?:string}>).detail;if(detail?.householdId&&detail.householdId!==householdId)return;void load()};const click=(event:MouseEvent)=>{if(!(event.target as HTMLElement|null)?.closest(".silvi-launcher"))return;localStorage.setItem(`kit-hub-silvi-tried:${householdId}`,"1");setState(current=>current?{...current,silvi:true}:current)};window.addEventListener("kit-hub-household-data-changed",changed);document.addEventListener("click",click);return()=>{dead=true;window.removeEventListener("kit-hub-household-data-changed",changed);document.removeEventListener("click",click)}},[householdId]);
 const steps=useMemo(()=>state?[{key:"invite",label:"Bring someone into the household",detail:"Shared use is where Kit Hub starts becoming useful.",done:state.members>1,Icon:UsersRound,event:"activation_family_invited" as ActivationEvent,action:()=>window.dispatchEvent(new Event("kit-hub-open-household"))},{key:"event",label:"Add the first calendar event",detail:"Give the household one thing to coordinate around.",done:state.events>0,Icon:CalendarPlus,event:"activation_first_event" as ActivationEvent,action:()=>window.dispatchEvent(new Event("kit-hub-open-calendar"))},{key:"task",label:"Create a shared task",detail:"Start with something small that somebody can actually complete.",done:state.tasks>0,Icon:ListPlus,event:"activation_first_task" as ActivationEvent,action:()=>window.dispatchEvent(new Event("kit-hub-open-tasks"))},{key:"meal",label:"Plan a meal",detail:"Connect dinner planning with the rest of the household week.",done:state.meals>0,Icon:Utensils,event:"activation_first_meal" as ActivationEvent,action:()=>window.dispatchEvent(new Event("kit-hub-open-meals"))},{key:"silvi",label:"Try Silvi once",detail:"Ask what is happening this week or add something with approval.",done:state.silvi,Icon:Sparkles,event:"activation_silvi_tried" as ActivationEvent,action:()=>document.querySelector<HTMLButtonElement>(".silvi-launcher")?.click()}]:[],[state]);
 useEffect(()=>{if(!state)return;const endpoint=`/api/v1/households/${encodeURIComponent(householdId)}/product-analytics`;const record=(eventKey:ActivationEvent)=>{const key=`kit-hub-activation:${householdId}:${eventKey}`;if(localStorage.getItem(key))return;localStorage.setItem(key,"1");void fetch(endpoint,{method:"POST",credentials:"include",keepalive:true,headers:{"content-type":"application/json"},body:JSON.stringify({eventKey})}).catch(()=>localStorage.removeItem(key))};for(const step of steps)if(step.done)record(step.event);if(steps.length&&steps.filter(step=>step.done).length>=3&&state.members>1)record("activation_household")},[householdId,state,steps]);
 if(!host||!state||hidden)return null;const completed=steps.filter(step=>step.done).length;if(completed===steps.length)return null;const next=steps.find(step=>!step.done);return createPortal(<section className="first-week-guide"><header><div className="first-week-guide__mark"><Sparkles/></div><div><small>YOUR FIRST WEEK</small><h2>{completed} of {steps.length} useful setup wins</h2><p>Skip the long tour. Do a few real household actions and discover features when they become relevant.</p></div><button aria-label="Hide first-week guide" onClick={()=>{localStorage.setItem(`kit-hub-first-week-hidden:${householdId}`,"1");setHidden(true)}}><X/></button></header><div className="first-week-guide__progress"><i style={{width:`${Math.round((completed/steps.length)*100)}%`}}/></div><div className="first-week-guide__steps">{steps.map(step=><button type="button" key={step.key} className={step.done?"is-done":step===next?"is-next":""} onClick={step.action}><span>{step.done?<Check/>:<step.Icon/>}</span><div><strong>{step.label}</strong><small>{step.done?"Done":step.detail}</small></div>{step.done&&<CheckCircle2/>}</button>)}</div>{next&&<footer><span><strong>Suggested next:</strong> {next.label}</span><button onClick={next.action}>Do this next →</button></footer>}</section>,host);
}
