import { useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";
import { CalendarPlus, Check, CheckCircle2, ListPlus, Sparkles, UsersRound, Utensils, X } from "lucide-react";
import { api } from "../lib/api";
import "../first-week-guide.css";

type State={members:number;events:number;tasks:number;meals:number;silvi:boolean};
function clickNav(term:string){const buttons=Array.from(document.querySelectorAll<HTMLButtonElement>(".sidebar-nav button,.mobile-nav button"));buttons.find(button=>button.textContent?.trim().toLowerCase().includes(term))?.click()}

export function FirstWeekGuide({householdId}:{householdId:string}){
 const[host,setHost]=useState<HTMLElement|null>(null),[state,setState]=useState<State|null>(null),[hidden,setHidden]=useState(()=>localStorage.getItem(`kit-hub-first-week-hidden:${householdId}`)==="1");
 const startedKey=`kit-hub-first-week-start:${householdId}`;
 useEffect(()=>{if(!localStorage.getItem(startedKey))localStorage.setItem(startedKey,String(Date.now()));const locate=()=>setHost(document.querySelector<HTMLElement>(".dashboard-widget-grid"));locate();const observer=new MutationObserver(locate);observer.observe(document.body,{childList:true,subtree:true});return()=>observer.disconnect()},[startedKey]);
 useEffect(()=>{let dead=false;async function load(){try{const[core,meals]=await Promise.all([api.everydayCore(householdId),api.meals(householdId)]);if(dead)return;setState({members:core.members.length,events:core.events.length,tasks:core.tasks.length,meals:meals.plans.length,silvi:localStorage.getItem(`kit-hub-silvi-tried:${householdId}`)==="1"})}catch{}}void load();const changed=(event:Event)=>{const detail=(event as CustomEvent<{householdId?:string}>).detail;if(detail?.householdId&&detail.householdId!==householdId)return;void load()};const click=(event:MouseEvent)=>{if(!(event.target as HTMLElement|null)?.closest(".silvi-launcher"))return;localStorage.setItem(`kit-hub-silvi-tried:${householdId}`,"1");setState(current=>current?{...current,silvi:true}:current)};window.addEventListener("kit-hub-household-data-changed",changed);document.addEventListener("click",click);return()=>{dead=true;window.removeEventListener("kit-hub-household-data-changed",changed);document.removeEventListener("click",click)}},[householdId]);
 const steps=useMemo(()=>state?[{key:"invite",label:"Bring someone into the household",detail:"Shared use is where Kit Hub starts becoming useful.",done:state.members>1,Icon:UsersRound,action:()=>clickNav("household")},{key:"event",label:"Add the first calendar event",detail:"Give the household one thing to coordinate around.",done:state.events>0,Icon:CalendarPlus,action:()=>clickNav("calendar")},{key:"task",label:"Create a shared task",detail:"Start with something small that somebody can actually complete.",done:state.tasks>0,Icon:ListPlus,action:()=>clickNav("task")},{key:"meal",label:"Plan a meal",detail:"Connect dinner planning with the rest of the household week.",done:state.meals>0,Icon:Utensils,action:()=>clickNav("meal")},{key:"silvi",label:"Try Silvi once",detail:"Ask what is happening this week or add something with approval.",done:state.silvi,Icon:Sparkles,action:()=>document.querySelector<HTMLButtonElement>(".silvi-launcher")?.click()}]:[],[state]);
 if(!host||!state||hidden)return null;const started=Number(localStorage.getItem(startedKey)||Date.now());if(Date.now()-started>7*86400000)return null;const completed=steps.filter(step=>step.done).length;if(completed===steps.length)return null;const next=steps.find(step=>!step.done);return createPortal(<section className="first-week-guide"><header><div className="first-week-guide__mark"><Sparkles/></div><div><small>YOUR FIRST WEEK</small><h2>{completed} of {steps.length} useful setup wins</h2><p>Skip the long tour. Do a few real household actions and discover features when they become relevant.</p></div><button aria-label="Hide first-week guide" onClick={()=>{localStorage.setItem(`kit-hub-first-week-hidden:${householdId}`,"1");setHidden(true)}}><X/></button></header><div className="first-week-guide__progress"><i style={{width:`${Math.round((completed/steps.length)*100)}%`}}/></div><div className="first-week-guide__steps">{steps.map(step=><button type="button" key={step.key} className={step.done?"is-done":step===next?"is-next":""} onClick={step.action}><span>{step.done?<Check/>:<step.Icon/>}</span><div><strong>{step.label}</strong><small>{step.done?"Done":step.detail}</small></div>{step.done&&<CheckCircle2/>}</button>)}</div>{next&&<footer><span><strong>Suggested next:</strong> {next.label}</span><button onClick={next.action}>Do this next →</button></footer>}</section>,host);
}
