import { useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";
import { ExternalLink, MapPin, ShieldCheck, UsersRound } from "lucide-react";
import "../privacy-sharing.css";

type PresenceItem={userId:string;name:string;status:string|null;statusExpiresAt:string|null;location:{latitude:number;longitude:number;accuracy:string;expiresAt:string}|null;own:boolean};
type PresenceResponse={presence:PresenceItem[]};
type PlaceLabel={label:string|null;city:string|null;country:string|null};

async function getJson<T>(url:string){const response=await fetch(url,{credentials:"include"});const body=await response.json().catch(()=>({})) as any;if(!response.ok)throw new Error(body?.error?.message||"Family status could not be loaded.");return body as T}
function storageKey(householdId:string){return `kit-hub-presence-home:${householdId}`}
function mapUrl(item:PresenceItem["location"]){return item?`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${item.latitude},${item.longitude}`)}`:"#"}

export function HouseholdPresenceHome({householdId}:{householdId:string}){
 const[target,setTarget]=useState<HTMLElement|null>(null),[enabled,setEnabled]=useState(()=>localStorage.getItem(storageKey(householdId))!=="0"),[presence,setPresence]=useState<PresenceItem[]>([]),[labels,setLabels]=useState<Record<string,string>>({}),[error,setError]=useState("");
 useEffect(()=>{const locate=()=>setTarget(document.querySelector<HTMLElement>(".dashboard-widget-grid"));locate();const observer=new MutationObserver(locate);observer.observe(document.body,{childList:true,subtree:true});return()=>observer.disconnect()},[]);
 useEffect(()=>{const changed=(event:Event)=>{const detail=(event as CustomEvent<{householdId?:string;enabled?:boolean}>).detail;if(detail?.householdId===householdId&&typeof detail.enabled==="boolean")setEnabled(detail.enabled)};window.addEventListener("kit-hub-presence-home-setting",changed);return()=>window.removeEventListener("kit-hub-presence-home-setting",changed)},[householdId]);
 async function load(){if(!enabled)return;try{const data=await getJson<PresenceResponse>(`/api/v1/households/${encodeURIComponent(householdId)}/presence`);setPresence(data.presence);setError("");const visible=data.presence.filter(item=>!item.own&&item.location);const next:Record<string,string>={};await Promise.all(visible.map(async item=>{const location=item.location;if(!location)return;try{const place=await getJson<PlaceLabel>(`/api/v1/places/reverse?lat=${encodeURIComponent(String(location.latitude))}&lon=${encodeURIComponent(String(location.longitude))}`);if(place.label)next[item.userId]=location.accuracy==="approximate"?`Near ${place.city||place.label}`:place.label}catch{}}));setLabels(next)}catch(e){setError(e instanceof Error?e.message:"Family status could not be loaded.")}}
 useEffect(()=>{void load();const timer=window.setInterval(()=>void load(),60000);const updated=()=>void load();window.addEventListener("kit-hub-presence-updated",updated);return()=>{window.clearInterval(timer);window.removeEventListener("kit-hub-presence-updated",updated)}},[householdId,enabled]);
 const visible=useMemo(()=>presence.filter(item=>!item.own&&(item.status||item.location)),[presence]);
 if(!target||!enabled)return null;
 return createPortal(<section className="dashboard-card dashboard-widget dashboard-widget--medium dashboard-widget-height--normal dashboard-widget--presence"><div className="dashboard-widget__content presence-home-widget"><header><div><small>LIVE FAMILY STATUS</small><h2>Who&apos;s where</h2></div><span><ShieldCheck/></span></header>{error?<p className="module-alert">{error}</p>:visible.length?<div className="presence-home-list">{visible.map(item=><article key={item.userId}><span className="presence-home-avatar">{item.name.slice(0,1).toUpperCase()}</span><div><strong>{item.name}</strong>{item.status&&<small>{item.status}</small>}{item.location&&<span className="presence-home-location"><MapPin/>{labels[item.userId]|| (item.location.accuracy==="approximate"?"Approximate location shared":"Precise location shared")}</span>}</div>{item.location&&<a href={mapUrl(item.location)} target="_blank" rel="noreferrer" aria-label={`Open ${item.name}'s shared location on map`}><ExternalLink/></a>}</article>)}</div>:<div className="presence-home-empty"><UsersRound/><strong>No one is sharing right now</strong><small>Status and location only appear here when a family member explicitly shares them with you.</small></div>}<footer><button type="button" onClick={()=>window.dispatchEvent(new Event("kit-hub-open-personal-settings"))}>Privacy & sharing</button><button type="button" onClick={()=>window.dispatchEvent(new Event("kit-hub-open-family-coordination"))}>Open family plan →</button></footer></div></section>,target);
}
