import { useEffect } from "react";
import { localeTag } from "../lib/i18n";
import { useKitLocale } from "../lib/use-kit-locale";

const ui:Record<string,Record<string,string>>={
 nl:{"Tasks / To-do":"Taken / To-do","A family to-do list that feels more like the note on the fridge.":"Een familielijst die meer aanvoelt als het briefje op de koelkast.","Add task":"Taak toevoegen","Loading…":"Laden…","No tasks yet.":"Nog geen taken.","Anyone":"Iedereen","Urgent":"Dringend","Groceries":"Boodschappen","Tick it off, scratch it out, and star the things nobody should forget.":"Vink af, streep door en geef een ster aan wat niemand mag vergeten.","Add item":"Item toevoegen","The grocery list is empty.":"De boodschappenlijst is leeg.","Add grocery":"Boodschap toevoegen","Meals & Dinner":"Maaltijden & avondeten","Plan a meal":"Maaltijd plannen","Today":"Vandaag","Breakfast":"Ontbijt","Lunch":"Lunch","Dinner":"Avondeten","Snack":"Tussendoortje","Add":"Toevoegen","Cookbook":"Kookboek","Favourite meals & recipes":"Favoriete maaltijden & recepten","Add recipe":"Recept toevoegen","Meal ideas":"Maaltijdideeën","Suggest":"Voorstellen","No meal ideas yet.":"Nog geen maaltijdideeën.","Household":"Huishouden","Direct messages":"Directe berichten","Announcements":"Aankondigingen","Activity":"Activiteit","Household chat":"Huishoudchat","No messages yet.":"Nog geen berichten.","Notifications":"Meldingen","New announcement":"Nieuwe aankondiging","Send":"Versturen","Emoji":"Emoji","Stickers":"Stickers","GIFs":"GIFs","Search":"Zoeken","Edit":"Bewerken","Save":"Opslaan","Cancel":"Annuleren","Delete":"Verwijderen"},
 fr:{"Tasks / To-do":"Tâches / À faire","Add task":"Ajouter une tâche","Loading…":"Chargement…","No tasks yet.":"Aucune tâche.","Anyone":"Tout le monde","Urgent":"Urgent","Groceries":"Courses","Add item":"Ajouter un article","The grocery list is empty.":"La liste de courses est vide.","Meals & Dinner":"Repas & dîner","Plan a meal":"Planifier un repas","Today":"Aujourd’hui","Breakfast":"Petit-déjeuner","Lunch":"Déjeuner","Dinner":"Dîner","Snack":"Collation","Add":"Ajouter","Cookbook":"Livre de recettes","Favourite meals & recipes":"Repas et recettes préférés","Add recipe":"Ajouter une recette","Meal ideas":"Idées de repas","Suggest":"Suggérer","No meal ideas yet.":"Aucune idée de repas.","Household":"Foyer","Direct messages":"Messages directs","Announcements":"Annonces","Activity":"Activité","Household chat":"Discussion du foyer","No messages yet.":"Aucun message.","Notifications":"Notifications","New announcement":"Nouvelle annonce","Send":"Envoyer","Search":"Rechercher","Edit":"Modifier","Save":"Enregistrer","Cancel":"Annuler","Delete":"Supprimer"},
 de:{"Tasks / To-do":"Aufgaben / To-do","Add task":"Aufgabe hinzufügen","Loading…":"Laden…","No tasks yet.":"Noch keine Aufgaben.","Anyone":"Alle","Urgent":"Dringend","Groceries":"Einkäufe","Add item":"Artikel hinzufügen","The grocery list is empty.":"Die Einkaufsliste ist leer.","Meals & Dinner":"Mahlzeiten & Abendessen","Plan a meal":"Mahlzeit planen","Today":"Heute","Breakfast":"Frühstück","Lunch":"Mittagessen","Dinner":"Abendessen","Snack":"Snack","Add":"Hinzufügen","Cookbook":"Kochbuch","Favourite meals & recipes":"Lieblingsgerichte & Rezepte","Add recipe":"Rezept hinzufügen","Meal ideas":"Essensideen","Suggest":"Vorschlagen","No meal ideas yet.":"Noch keine Essensideen.","Household":"Haushalt","Direct messages":"Direktnachrichten","Announcements":"Ankündigungen","Activity":"Aktivität","Household chat":"Haushaltschat","No messages yet.":"Noch keine Nachrichten.","Notifications":"Benachrichtigungen","New announcement":"Neue Ankündigung","Send":"Senden","Search":"Suchen","Edit":"Bearbeiten","Save":"Speichern","Cancel":"Abbrechen","Delete":"Löschen"},
 es:{"Tasks / To-do":"Tareas / Pendientes","Add task":"Añadir tarea","Loading…":"Cargando…","No tasks yet.":"Aún no hay tareas.","Anyone":"Cualquiera","Urgent":"Urgente","Groceries":"Compras","Add item":"Añadir artículo","The grocery list is empty.":"La lista de compras está vacía.","Meals & Dinner":"Comidas y cena","Plan a meal":"Planificar una comida","Today":"Hoy","Breakfast":"Desayuno","Lunch":"Almuerzo","Dinner":"Cena","Snack":"Merienda","Add":"Añadir","Cookbook":"Recetario","Favourite meals & recipes":"Comidas y recetas favoritas","Add recipe":"Añadir receta","Meal ideas":"Ideas de comidas","Suggest":"Sugerir","No meal ideas yet.":"Aún no hay ideas de comidas.","Household":"Hogar","Direct messages":"Mensajes directos","Announcements":"Anuncios","Activity":"Actividad","Household chat":"Chat del hogar","No messages yet.":"Aún no hay mensajes.","Notifications":"Notificaciones","New announcement":"Nuevo anuncio","Send":"Enviar","Search":"Buscar","Edit":"Editar","Save":"Guardar","Cancel":"Cancelar","Delete":"Eliminar"}
};
const original=new WeakMap<Text,string>();
function translateSurface(language:string){const map=ui[language];document.documentElement.lang=language;if(!map)return;const root=document.querySelector(".app-shell");if(!root)return;const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let node:Node|null;while((node=walker.nextNode())){const text=node as Text;const parent=text.parentElement;if(!parent||["SCRIPT","STYLE","TEXTAREA","INPUT","OPTION"].includes(parent.tagName))continue;const raw=(original.get(text)??text.data).trim();if(!raw)continue;if(!original.has(text))original.set(text,text.data);const replacement=map[raw];if(replacement)text.data=text.data.replace(raw,replacement)}}
export function LocalizedSurface(){const locale=useKitLocale();useEffect(()=>{const frame=requestAnimationFrame(()=>translateSurface(locale.language));const observer=new MutationObserver(()=>translateSurface(locale.language));observer.observe(document.body,{subtree:true,childList:true});return()=>{cancelAnimationFrame(frame);observer.disconnect()}},[locale.language]);useEffect(()=>{document.documentElement.lang=locale.language;document.documentElement.dataset.kitLocale=localeTag(locale)},[locale]);return null}
