import { CalendarDays, CheckSquare2, ChefHat, HeartHandshake, Home, LockKeyhole, MessageCircleMore, ShieldCheck, Sparkles, UsersRound } from "lucide-react";
import { Brand } from "./Brand";
import "../public-product-page.css";

const features=[
  {Icon:CalendarDays,title:"One household calendar",text:"Keep events, appointments and family plans together without turning the home screen into a corporate calendar."},
  {Icon:CheckSquare2,title:"Tasks that belong to real people",text:"Shared tasks, routines and household coordination make ownership visible without turning family life into a leaderboard."},
  {Icon:ChefHat,title:"Meals and groceries together",text:"Plan dinners, save recipes and connect ingredients to the grocery list."},
  {Icon:MessageCircleMore,title:"A private family hub",text:"Messages, notes, announcements and everyday updates live beside the practical parts of the household."},
  {Icon:Sparkles,title:"Silvi helps, but asks first",text:"Kit Hub can suggest plans and changes while keeping confirmation in the hands of household members."},
  {Icon:UsersRound,title:"Personal and shared spaces",text:"People can keep their own preferences while sharing only what actually belongs to the household."},
];

export function PublicProductPage(){return <main className="public-product-page">
  <nav className="public-product-nav"><Brand/><div><a href="#privacy">Privacy</a><a href="#beta">Private beta</a><a className="public-product-open" href="/">Open Kit Hub</a></div></nav>
  <section className="public-product-hero"><div><small>THE FAMILY PLATFORM</small><h1>Your household has a lot going on. Kit Hub gives it one shared home.</h1><p>Calendar, tasks, meals, groceries, notes, family communication and coordination — designed as a private family operating system rather than a pile of disconnected lists.</p><div className="public-product-actions"><a href="/">Open Kit Hub</a><a href="#beta">About the beta</a></div><span><ShieldCheck/>Built privacy-first · Private beta</span></div><aside aria-label="Kit Hub feature preview"><div className="public-preview-top"><Home/><strong>Today at home</strong><span>Tuesday</span></div><div className="public-preview-grid"><article><CalendarDays/><b>3</b><span>Upcoming events</span></article><article><CheckSquare2/><b>5</b><span>Open tasks</span></article><article><ChefHat/><b>4</b><span>Dinners planned</span></article><article><HeartHandshake/><b>1</b><span>Family focus</span></article></div><div className="public-preview-note"><Sparkles/><span><strong>Family plan</strong><small>See what needs attention without exposing private family content.</small></span></div></aside></section>
  <section className="public-product-features"><header><small>BUILT FOR EVERYDAY FAMILY LIFE</small><h2>Shared when it should be. Personal when it should stay personal.</h2></header><div>{features.map(({Icon,title,text})=><article key={title}><Icon/><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className="public-product-privacy" id="privacy"><div><LockKeyhole/><small>PRIVACY BY DESIGN</small><h2>Your family data is not product analytics.</h2><p>Kit Hub’s product analytics are deliberately limited to aggregate household/day counters from a fixed list of product actions. They do not record family messages, notes, search text, task or event titles, shared locations, or other household content.</p></div><ul><li><ShieldCheck/><span><strong>Location sharing is optional</strong><small>Status and location sharing are separate, temporary and controlled by the person sharing.</small></span></li><li><ShieldCheck/><span><strong>No location history by default</strong><small>Current shared location replaces the previous current location rather than building a movement history.</small></span></li><li><ShieldCheck/><span><strong>AI changes require confirmation</strong><small>Silvi can prepare actions, but household changes are confirmed before execution.</small></span></li></ul></section>
  <section className="public-product-beta" id="beta"><small>PRIVATE BETA</small><h2>We’re building for return visits, not signup numbers.</h2><p>Kit Hub is being tested with a small number of households while we improve coordination, reliability and privacy. Beta access can be restricted to invited email addresses from the Kit Hub Admin control room.</p><a href="/">Already invited? Open Kit Hub</a></section>
  <footer><Brand/><span>Kit Hub Family Platform · Beta product page</span></footer>
</main>}
