export type HouseholdRole = "owner" | "admin" | "adult" | "teen" | "child" | "guest";
export interface HouseholdSummary { id:string; name:string; slug:string; role:HouseholdRole; memberCount:number; defaultLanguage:string; timezone:string; theme:string; }
export interface BootstrapResponse { user:{id:string;name:string;email:string;image:string|null}; households:HouseholdSummary[]; activeHousehold:HouseholdSummary|null; }
export interface CreateHouseholdInput { name:string; timezone:string; defaultLanguage:string; }
export interface UpdateHouseholdInput { name:string; }
export interface UpdateHouseholdResponse { id:string; name:string; }
export interface ApiErrorBody { error:{code:string;message:string;requestId:string;details?:Record<string,string>}; }
export interface AppVersionResponse { id:string;tag:string|null;timestamp:string|null; }
export interface AdminReleaseStep { name:string;status:string;conclusion:string|null;number:number; }
export interface AdminReleaseFailure { step:string;summary:string;excerpt:string|null; }
export interface AdminReleaseRun { id:number;name:string;status:string;conclusion:string|null;headBranch:string;htmlUrl:string|null;createdAt:string|null;updatedAt:string|null;steps:AdminReleaseStep[];failure:AdminReleaseFailure|null; }
export interface AdminPublishPullRequest { number:number;title:string;headBranch:string;headSha:string;baseBranch:string;htmlUrl:string;author:string|null;updatedAt:string|null;draft:boolean;mergeable:boolean|null;checkState:"success"|"pending"|"failure"|"missing";checkSummary:string;ready:boolean;blockers:string[]; }
export interface AdminReleaseStatusResponse { releaseConfigured:boolean;publishConfigured:boolean;publishStatus:"available"|"no_changes"|"unavailable";repository:string|null;workflow:string|null;deployedVersion:AppVersionResponse;latestRun:AdminReleaseRun|null;pullRequests:AdminPublishPullRequest[];publishStatusMessage:string|null; }
export interface AdminReleaseDispatchInput { pullNumber?:number;headSha?:string; }
export interface AdminReleaseDispatchResponse { accepted:boolean;message:string;published:{pullNumber:number;sha:string}|null; }
export interface AdminReleaseCancelResponse { cancelled:boolean;message:string; }
export interface HouseholdMemberSummary { id:string;userId:string;name:string;email:string;role:HouseholdRole;joinedAt:string|null; }
export interface EverydayTask { id:string;title:string;notes:string|null;status:"todo"|"done";priority:"low"|"normal"|"high";dueAt:string|null;assigneeUserId:string|null;assigneeName:string|null;createdAt:string; }
export interface GroceryItem { id:string;name:string;quantity:string;checked:boolean;important:boolean;createdAt:string; }
export type EventType="event"|"birthday"|"happening"|"appointment"|"school"|"pet"|"meal"|"holiday"; export type EventRecurrence="none"|"daily"|"weekly"|"monthly"|"yearly";
export interface HouseholdEvent { id:string;title:string;description:string|null;location:string|null;startsAt:string;endsAt:string|null;allDay:boolean;eventType:EventType;recurrence:EventRecurrence;reminderMinutes:number|null;createdAt:string; }
export interface EverydayCoreResponse { members:HouseholdMemberSummary[];tasks:EverydayTask[];groceries:GroceryItem[];events:HouseholdEvent[]; }
export interface CreateTaskInput { title:string;notes?:string;priority?:"low"|"normal"|"high";dueAt?:string|null;assigneeUserId?:string|null; } export interface CreateGroceryItemInput { name:string;quantity?:string;important?:boolean; } export interface CreateEventInput { title:string;description?:string;location?:string;startsAt:string;endsAt?:string|null;allDay?:boolean;eventType?:EventType;recurrence?:EventRecurrence;reminderMinutes?:number|null; }
export interface FamilyNote { id:string;body:string;authorUserId:string;authorName:string;createdAt:string;updatedAt:string; } export interface HouseholdFocus { title:string;details:string|null;updatedByUserId:string;updatedByName:string;updatedAt:string; } export interface HouseholdHomeResponse { notes:FamilyNote[];focus:HouseholdFocus|null;canManage:boolean; } export interface SaveFamilyNoteInput { body:string; } export interface SaveHouseholdFocusInput { title:string;details?:string; }
export type MealType="breakfast"|"lunch"|"dinner"|"snack"; export interface MealIngredient { name:string;quantity:string; } export interface MealRecipe { id:string;name:string;description:string|null;ingredients:MealIngredient[];instructions:string|null;favorite:boolean;createdBy:string;createdAt:string;updatedAt:string; } export interface MealPlan { id:string;mealDate:string;mealType:MealType;title:string;recipeId:string|null;recipeName:string|null;cookUserId:string|null;cookName:string|null;notes:string|null;reminderMinutes:number|null;createdAt:string;updatedAt:string; } export interface MealSuggestion { id:string;title:string;notes:string|null;mealType:MealType;suggestedByUserId:string;suggestedByName:string;votes:number;votedByMe:boolean;createdAt:string; } export interface MealPlannerResponse { plans:MealPlan[];recipes:MealRecipe[];suggestions:MealSuggestion[];dietaryNotes:string|null;canManage:boolean; } export interface SaveMealPlanInput { mealDate:string;mealType:MealType;title:string;recipeId?:string|null;cookUserId?:string|null;notes?:string;reminderMinutes?:number|null; } export interface SaveMealRecipeInput { name:string;description?:string;ingredients:MealIngredient[];instructions?:string;favorite?:boolean; } export interface SaveMealSuggestionInput { title:string;notes?:string;mealType?:MealType; } export interface SaveMealSettingsInput { dietaryNotes:string; } export interface AddRecipeIngredientsResponse { items:GroceryItem[];addedCount:number; }
export interface MessageReaction { emoji:string;count:number;reactedByMe:boolean; }
export interface HouseholdMessage { id:string;body:string;authorUserId:string;authorName:string;createdAt:string;editedAt:string|null;reactions?:MessageReaction[];mentionedUserIds?:string[];mentionsMe?:boolean; }
export interface HouseholdAnnouncement { id:string;title:string;body:string;pinned:boolean;createdBy:string;createdByName:string;createdAt:string;updatedAt:string; } export interface HouseholdActivityItem { id:string;kind:string;summary:string;actorUserId:string|null;actorName:string|null;createdAt:string; } export interface DirectConversation { userId:string;name:string;role:HouseholdRole;lastMessage:string|null;lastMessageAt:string|null;unreadCount:number; } export interface DirectMessage { id:string;senderUserId:string;senderName:string;recipientUserId:string;recipientName:string;body:string;createdAt:string; }
export interface NotificationPreferences { householdChat:boolean;announcements:boolean;activity:boolean;calendar:boolean;tasks:boolean;groceries:boolean;meals:boolean; }
export interface NotificationPreferencesResponse { preferences:NotificationPreferences; essential:{mentions:boolean;directMessages:boolean;assignedToMe:boolean}; }
export interface HouseholdCommunicationResponse { messages:HouseholdMessage[];announcements:HouseholdAnnouncement[];activity:HouseholdActivityItem[];directConversations?:DirectConversation[];unreadCount:number;directUnreadCount?:number;mentionUnreadCount?:number;canSend:boolean;canAnnounce:boolean; }
export interface DirectMessagesResponse { messages:DirectMessage[];peer:{userId:string;name:string;role:HouseholdRole};canSend:boolean; } export interface CreateHouseholdMessageInput { body:string;mentionedUserIds?:string[]; } export interface CreateHouseholdAnnouncementInput { title:string;body:string; } export interface CreateDirectMessageInput { body:string; }
