import { Hono } from "hono";
import { createAuth } from "./auth";
import { requirePlatformAdmin } from "./admin";
import { apiError, type AppBindings } from "./http";

const app=new Hono<AppBindings>();
type Ctx=Parameters<typeof apiError>[0];
const reliabilityKeys=new Set(["client_error","api_error","silvi_error","release_error","slow_view","failed_refresh"]);
const templateKeys=new Set(["welcome","beta_update","release_note"]);
function clean(v:unknown,max=160){return typeof v==="string"?v.trim().slice(0,max):""}
async function session(c:Ctx){return(await createAuth(c.env,c.req.raw).api.getSession({headers:c.req.raw.headers}))?.user??null}
function bool(v:unknown){return v===true||v===1||v==="1"||v==="true"}
function esc(v:string){return v.replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[ch]||ch))}
function template(kind:string,name:string|null){const who=name?` ${name}`:"";if(kind==="welcome")return{subject:"Welcome to the Kit Hub private beta",html:`<h2>Welcome${esc(who)} to Kit Hub</h2><p>Your private-beta access is ready. Start with one shared workflow: add an event, task, grocery item or meal, then invite your household when you are comfortable.</p><p>Silvi can suggest changes, but household changes still require approval.</p>`};if(kind==="beta_update")return{subject:"Kit Hub private beta update",html:`<h2>Kit Hub beta update</h2><p>We are continuing to improve family coordination, Silvi actions, desktop readability and beta reliability.</p><p>If something feels confusing or breaks, please use the in-app feedback tool so we can connect the report to the current release.</p>`};return{subject:"What changed in Kit Hub",html:`<h2>A meaningful Kit Hub update</h2><p>Kit Hub has new improvements ready for testing. Open the app to see the latest household coordination and reliability changes.</p>`}}
function preferenceColumn(kind:string){return kind==="welcome"?"welcome_opt_in":kind==="beta_update"?"beta_updates_opt_in":"release_notes_opt_in"}

app.get("/api/v1/beta-email-preferences",async c=>{const user=await session(c);if(!user)return apiError(c,401,"AUTH_REQUIRED","Sign in to manage email preferences.");const row=await c.env.DB.prepare("SELECT welcome_opt_in welcomeOptIn,beta_updates_opt_in betaUpdatesOptIn,release_notes_opt_in releaseNotesOptIn,unsubscribed_at unsubscribedAt FROM beta_email_preferences WHERE lower(email)=lower(?)").bind(user.email).first<any>();return c.json(row?{welcomeOptIn:Boolean(row.welcomeOptIn),betaUpdatesOptIn:Boolean(row.betaUpdatesOptIn),releaseNotesOptIn:Boolean(row.releaseNotesOptIn),unsubscribedAt:row.unsubscribedAt??null}:{welcomeOptIn:true,betaUpdatesOptIn:true,releaseNotesOptIn:true,unsubscribedAt:null})});
app.put("/api/v1/beta-email-preferences",async c=>{const user=await session(c);if(!user)return apiError(c,401,"AUTH_REQUIRED","Sign in to manage email preferences.");const body=await c.req.json().catch(()=>null) as Record<string,unknown>|null;if(!body)return apiError(c,422,"VALIDATION_FAILED","Choose your email preferences.");const current=await c.env.DB.prepare("SELECT welcome_opt_in welcomeOptIn,beta_updates_opt_in betaUpdatesOptIn,release_notes_opt_in releaseNotesOptIn FROM beta_email_preferences WHERE lower(email)=lower(?)").bind(user.email).first<any>();const welcome=Object.prototype.hasOwnProperty.call(body,"welcomeOptIn")?bool(body.welcomeOptIn):Boolean(current?.welcomeOptIn??1),updates=Object.prototype.hasOwnProperty.call(body,"betaUpdatesOptIn")?bool(body.betaUpdatesOptIn):Boolean(current?.betaUpdatesOptIn??1),release=Object.prototype.hasOwnProperty.call(body,"releaseNotesOptIn")?bool(body.releaseNotesOptIn):Boolean(current?.releaseNotesOptIn??1),allOff=!welcome&&!updates&&!release;await c.env.DB.prepare("INSERT INTO beta_email_preferences(email,welcome_opt_in,beta_updates_opt_in,release_notes_opt_in,updated_at,unsubscribed_at) VALUES(?,?,?,?,datetime('now'),?) ON CONFLICT(email) DO UPDATE SET welcome_opt_in=excluded.welcome_opt_in,beta_updates_opt_in=excluded.beta_updates_opt_in,release_notes_opt_in=excluded.release_notes_opt_in,updated_at=datetime('now'),unsubscribed_at=excluded.unsubscribed_at").bind(user.email,welcome?1:0,updates?1:0,release?1:0,allOff?new Date().toISOString():null).run();return c.json({welcomeOptIn:welcome,betaUpdatesOptIn:updates,releaseNotesOptIn:release,unsubscribed:allOff})});

app.post("/api/v1/reliability",async c=>{const user=await session(c);if(!user)return apiError(c,401,"AUTH_REQUIRED","Sign in to report reliability metrics.");const body=await c.req.json().catch(()=>null) as {metricKey?:unknown}|null,key=clean(body?.metricKey,40);if(!reliabilityKeys.has(key))return apiError(c,422,"RELIABILITY_EVENT_NOT_ALLOWED","That reliability metric is not supported.");const day=new Date().toISOString().slice(0,10);await c.env.DB.prepare("INSERT INTO app_reliability_daily(metric_date,metric_key,metric_count,last_seen_at) VALUES(?,?,1,datetime('now')) ON CONFLICT(metric_date,metric_key) DO UPDATE SET metric_count=app_reliability_daily.metric_count+1,last_seen_at=datetime('now')").bind(day,key).run();return c.json({recorded:true})});

app.post("/api/v1/admin/beta-email/send",async c=>{const admin=await requirePlatformAdmin(c);if(admin.response)return admin.response;const body=await c.req.json().catch(()=>null) as {email?:unknown;templateKey?:unknown}|null,email=clean(body?.email,254).toLowerCase(),templateKey=clean(body?.templateKey,30);if(!/^\S+@\S+\.\S+$/.test(email)||!templateKeys.has(templateKey))return apiError(c,422,"BETA_EMAIL_INVALID","Choose a beta tester and a supported email template.");const tester=await c.env.DB.prepare("SELECT display_name displayName,status FROM beta_tester_allowlist WHERE lower(email)=lower(?)").bind(email).first<{displayName:string|null;status:string}>();if(!tester||tester.status==="paused")return apiError(c,404,"BETA_TESTER_NOT_AVAILABLE","That beta tester is not currently available for email.");const pref=await c.env.DB.prepare(`SELECT ${preferenceColumn(templateKey)} allowed FROM beta_email_preferences WHERE lower(email)=lower(?)`).bind(email).first<{allowed:number}>();if(pref&& !Boolean(pref.allowed))return apiError(c,409,"BETA_EMAIL_OPTED_OUT","That tester opted out of this type of email.");const env=c.env as any,apiKey=clean(env.RESEND_API_KEY,500),from=clean(env.TRANSACTIONAL_EMAIL_FROM||env.EMAIL_FROM,254);if(!apiKey||!from)return apiError(c,409,"EMAIL_PROVIDER_NOT_CONFIGURED","Set RESEND_API_KEY and TRANSACTIONAL_EMAIL_FROM before sending beta email.");const content=template(templateKey,tester.displayName);const html=`${content.html}<hr><p style="font-size:12px;color:#667">Optional beta email. Change these choices in Kit Hub → My personal settings → Beta emails.</p>`;let response:Response;try{response=await fetch("https://api.resend.com/emails",{method:"POST",headers:{"content-type":"application/json","authorization":`Bearer ${apiKey}`},body:JSON.stringify({from,to:[email],subject:content.subject,html,tags:[{name:"category",value:`kit_hub_${templateKey}`}]})})}catch{return apiError(c,500,"EMAIL_PROVIDER_UNAVAILABLE","The transactional email provider could not be reached.")}const result=await response.json().catch(()=>({})) as any;if(!response.ok){await c.env.DB.prepare("INSERT INTO beta_email_delivery_log(id,email,template_key,status) VALUES(?,?,?,'failed')").bind(crypto.randomUUID(),email,templateKey).run();return apiError(c,500,"EMAIL_SEND_FAILED",clean(result?.message,240)||"The transactional email provider rejected the message.")}await c.env.DB.prepare("INSERT INTO beta_email_delivery_log(id,email,template_key,provider_message_id,status) VALUES(?,?,?,?, 'sent')").bind(crypto.randomUUID(),email,templateKey,clean(result?.id,120)||null).run();return c.json({sent:true,email,templateKey,providerMessageId:result?.id??null})});

app.get("/api/v1/admin/beta-readiness",async c=>{const admin=await requirePlatformAdmin(c);if(admin.response)return admin.response;const [testers,prefs,reliability,deliveries]=await Promise.all([c.env.DB.prepare("SELECT COUNT(*) total,SUM(CASE WHEN status='active' THEN 1 ELSE 0 END) active FROM beta_tester_allowlist").first<any>(),c.env.DB.prepare("SELECT COUNT(*) configured,SUM(welcome_opt_in) welcome,SUM(beta_updates_opt_in) updates,SUM(release_notes_opt_in) releases,SUM(CASE WHEN welcome_opt_in=0 AND beta_updates_opt_in=0 AND release_notes_opt_in=0 THEN 1 ELSE 0 END) unsubscribed FROM beta_email_preferences").first<any>(),c.env.DB.prepare("SELECT metric_key metricKey,SUM(metric_count) count FROM app_reliability_daily WHERE metric_date>=date('now','-6 day') GROUP BY metric_key ORDER BY count DESC").all<any>(),c.env.DB.prepare("SELECT COUNT(*) sent FROM beta_email_delivery_log WHERE status='sent' AND created_at>=datetime('now','-30 day')").first<any>()]);const env=c.env as any;const providerConfigured=Boolean(env.RESEND_API_KEY&& (env.TRANSACTIONAL_EMAIL_FROM||env.EMAIL_FROM));return c.json({email:{providerConfigured,providerName:providerConfigured?"Resend":null,testers:Number(testers?.total??0),activeTesters:Number(testers?.active??0),preferencesConfigured:Number(prefs?.configured??0),welcomeOptIn:Number(prefs?.welcome??0),betaUpdatesOptIn:Number(prefs?.updates??0),releaseNotesOptIn:Number(prefs?.releases??0),fullyUnsubscribed:Number(prefs?.unsubscribed??0),sentLast30Days:Number(deliveries?.sent??0)},reliability:{days:7,metrics:reliability.results.map((row:any)=>({metricKey:row.metricKey,count:Number(row.count)}))},privacyNote:"Reliability metrics are fixed counters only. They do not include messages, titles, locations, searches, notes, or household content."})});
export default app;
