import { Hono } from "hono";
import { createAuth } from "./auth";
import { requirePlatformAdmin } from "./admin";
import { apiError, type AppBindings } from "./http";

const app=new Hono<AppBindings>();
type Ctx=Parameters<typeof apiError>[0];
const reliabilityKeys=new Set(["client_error","api_error","silvi_error","release_error","slow_view","failed_refresh"]);
function clean(v:unknown,max=80){return typeof v==="string"?v.trim().slice(0,max):""}
async function session(c:Ctx){return(await createAuth(c.env,c.req.raw).api.getSession({headers:c.req.raw.headers}))?.user??null}
function bool(v:unknown){return v===true||v===1||v==="1"||v==="true"}

app.get("/api/v1/beta-email-preferences",async c=>{const user=await session(c);if(!user)return apiError(c,401,"AUTH_REQUIRED","Sign in to manage email preferences.");const row=await c.env.DB.prepare("SELECT welcome_opt_in welcomeOptIn,beta_updates_opt_in betaUpdatesOptIn,release_notes_opt_in releaseNotesOptIn,unsubscribed_at unsubscribedAt FROM beta_email_preferences WHERE lower(email)=lower(?)").bind(user.email).first<any>();return c.json(row?{welcomeOptIn:Boolean(row.welcomeOptIn),betaUpdatesOptIn:Boolean(row.betaUpdatesOptIn),releaseNotesOptIn:Boolean(row.releaseNotesOptIn),unsubscribedAt:row.unsubscribedAt??null}:{welcomeOptIn:true,betaUpdatesOptIn:true,releaseNotesOptIn:true,unsubscribedAt:null})});
app.put("/api/v1/beta-email-preferences",async c=>{const user=await session(c);if(!user)return apiError(c,401,"AUTH_REQUIRED","Sign in to manage email preferences.");const body=await c.req.json().catch(()=>null) as Record<string,unknown>|null;if(!body)return apiError(c,422,"VALIDATION_FAILED","Choose your email preferences.");const current=await c.env.DB.prepare("SELECT welcome_opt_in welcomeOptIn,beta_updates_opt_in betaUpdatesOptIn,release_notes_opt_in releaseNotesOptIn FROM beta_email_preferences WHERE lower(email)=lower(?)").bind(user.email).first<any>();const welcome=Object.prototype.hasOwnProperty.call(body,"welcomeOptIn")?bool(body.welcomeOptIn):Boolean(current?.welcomeOptIn??1),updates=Object.prototype.hasOwnProperty.call(body,"betaUpdatesOptIn")?bool(body.betaUpdatesOptIn):Boolean(current?.betaUpdatesOptIn??1),release=Object.prototype.hasOwnProperty.call(body,"releaseNotesOptIn")?bool(body.releaseNotesOptIn):Boolean(current?.releaseNotesOptIn??1),allOff=!welcome&&!updates&&!release;await c.env.DB.prepare("INSERT INTO beta_email_preferences(email,welcome_opt_in,beta_updates_opt_in,release_notes_opt_in,updated_at,unsubscribed_at) VALUES(?,?,?,?,datetime('now'),?) ON CONFLICT(email) DO UPDATE SET welcome_opt_in=excluded.welcome_opt_in,beta_updates_opt_in=excluded.beta_updates_opt_in,release_notes_opt_in=excluded.release_notes_opt_in,updated_at=datetime('now'),unsubscribed_at=excluded.unsubscribed_at").bind(user.email,welcome?1:0,updates?1:0,release?1:0,allOff?new Date().toISOString():null).run();return c.json({welcomeOptIn:welcome,betaUpdatesOptIn:updates,releaseNotesOptIn:release,unsubscribed:allOff})});

app.post("/api/v1/reliability",async c=>{const user=await session(c);if(!user)return apiError(c,401,"AUTH_REQUIRED","Sign in to report reliability metrics.");const body=await c.req.json().catch(()=>null) as {metricKey?:unknown}|null,key=clean(body?.metricKey,40);if(!reliabilityKeys.has(key))return apiError(c,422,"RELIABILITY_EVENT_NOT_ALLOWED","That reliability metric is not supported.");const day=new Date().toISOString().slice(0,10);await c.env.DB.prepare("INSERT INTO app_reliability_daily(metric_date,metric_key,metric_count,last_seen_at) VALUES(?,?,1,datetime('now')) ON CONFLICT(metric_date,metric_key) DO UPDATE SET metric_count=app_reliability_daily.metric_count+1,last_seen_at=datetime('now')").bind(day,key).run();return c.json({recorded:true})});

app.get("/api/v1/admin/beta-readiness",async c=>{const admin=await requirePlatformAdmin(c);if(admin.response)return admin.response;const [testers,prefs,reliability]=await Promise.all([c.env.DB.prepare("SELECT COUNT(*) total,SUM(CASE WHEN status='active' THEN 1 ELSE 0 END) active FROM beta_tester_allowlist").first<any>(),c.env.DB.prepare("SELECT COUNT(*) configured,SUM(welcome_opt_in) welcome,SUM(beta_updates_opt_in) updates,SUM(release_notes_opt_in) releases,SUM(CASE WHEN welcome_opt_in=0 AND beta_updates_opt_in=0 AND release_notes_opt_in=0 THEN 1 ELSE 0 END) unsubscribed FROM beta_email_preferences").first<any>(),c.env.DB.prepare("SELECT metric_key metricKey,SUM(metric_count) count FROM app_reliability_daily WHERE metric_date>=date('now','-6 day') GROUP BY metric_key ORDER BY count DESC").all<any>()]);const env=c.env as any;const providerConfigured=Boolean(env.RESEND_API_KEY||env.POSTMARK_SERVER_TOKEN||env.TRANSACTIONAL_EMAIL_API_KEY);return c.json({email:{providerConfigured,providerName:env.RESEND_API_KEY?"Resend":env.POSTMARK_SERVER_TOKEN?"Postmark":env.TRANSACTIONAL_EMAIL_API_KEY?"Custom provider":null,testers:Number(testers?.total??0),activeTesters:Number(testers?.active??0),preferencesConfigured:Number(prefs?.configured??0),welcomeOptIn:Number(prefs?.welcome??0),betaUpdatesOptIn:Number(prefs?.updates??0),releaseNotesOptIn:Number(prefs?.releases??0),fullyUnsubscribed:Number(prefs?.unsubscribed??0)},reliability:{days:7,metrics:reliability.results.map((row:any)=>({metricKey:row.metricKey,count:Number(row.count)}))},privacyNote:"Reliability metrics are fixed counters only. They do not include messages, titles, locations, searches, notes, or household content."})});
export default app;
