import { Hono } from "hono";
import { createAuth } from "./auth";
import { apiError, type AppBindings } from "./http";

const app=new Hono<AppBindings>();
type Ctx=Parameters<typeof apiError>[0];
async function currentUser(c:Ctx){return (await createAuth(c.env,c.req.raw).api.getSession({headers:c.req.raw.headers}))?.user??null}
async function isMember(c:Ctx,householdId:string,userId:string){return c.env.DB.prepare("SELECT 1 FROM memberships WHERE household_id=? AND user_id=? AND status='active'").bind(householdId,userId).first()}
async function access(c:Ctx){const user=await currentUser(c);if(!user)return{response:apiError(c,401,"AUTH_REQUIRED","Sign in to use chat media.")};const householdId=c.req.param("householdId")??"";if(!(await isMember(c,householdId,user.id)))return{response:apiError(c,403,"HOUSEHOLD_VIEW_REQUIRED","You do not have access to this household.")};return{user,householdId}}
function decodeBase64(value:string){const raw=atob(value);const bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);return bytes}

app.get("/api/v1/households/:householdId/chat-attachments",async c=>{const a=await access(c);if(a.response)return a.response;const rows=await c.env.DB.prepare(`SELECT a.id,a.entity_id messageId,a.file_name fileName,a.mime_type mimeType,a.size_bytes sizeBytes,a.created_at createdAt FROM household_attachments a JOIN household_messages m ON m.id=a.entity_id AND m.household_id=a.household_id WHERE a.household_id=? AND a.entity_type='message' ORDER BY a.created_at DESC LIMIT 300`).bind(a.householdId).all();return c.json({items:rows.results})});

app.post("/api/v1/households/:householdId/messages/:messageId/attachments",async c=>{const a=await access(c);if(a.response)return a.response;const message=await c.env.DB.prepare("SELECT author_user_id authorUserId FROM household_messages WHERE id=? AND household_id=?").bind(c.req.param("messageId"),a.householdId).first<{authorUserId:string}>();if(!message)return apiError(c,404,"MESSAGE_NOT_FOUND","That message could not be found.");if(message.authorUserId!==a.user.id)return apiError(c,403,"ATTACHMENT_OWNER_REQUIRED","You can only attach files to your own messages.");const existing=await c.env.DB.prepare("SELECT COUNT(*) count FROM household_attachments WHERE household_id=? AND entity_type='message' AND entity_id=?").bind(a.householdId,c.req.param("messageId")).first<{count:number}>();if(Number(existing?.count??0)>=3)return apiError(c,422,"ATTACHMENT_LIMIT","A chat message can contain up to 3 attachments.");const body=await c.req.json().catch(()=>null) as Record<string,unknown>|null;if(!body||typeof body.fileName!=="string"||typeof body.mimeType!=="string"||typeof body.dataBase64!=="string")return apiError(c,422,"VALIDATION_FAILED","Choose a valid image or file.");const allowed=["image/png","image/jpeg","image/webp","image/gif","application/pdf","text/plain"];if(!allowed.includes(body.mimeType))return apiError(c,422,"FILE_TYPE_NOT_ALLOWED","Use PNG, JPG, WebP, GIF, PDF or text files.");const size=Math.floor(body.dataBase64.length*3/4);if(size<1||size>1572864)return apiError(c,422,"FILE_TOO_LARGE","Chat attachments can be up to 1.5 MB each.");const id=crypto.randomUUID();await c.env.DB.prepare("INSERT INTO household_attachments(id,household_id,uploaded_by,entity_type,entity_id,file_name,mime_type,size_bytes,data_base64) VALUES(?,?,?,?,?,?,?,?,?)").bind(id,a.householdId,a.user.id,"message",c.req.param("messageId"),body.fileName.slice(0,180),body.mimeType,size,body.dataBase64).run();return c.json({id,messageId:c.req.param("messageId"),fileName:body.fileName,mimeType:body.mimeType,sizeBytes:size,createdAt:new Date().toISOString()},201)});

app.get("/api/v1/households/:householdId/chat-attachments/:attachmentId",async c=>{const a=await access(c);if(a.response)return a.response;const row=await c.env.DB.prepare(`SELECT a.file_name fileName,a.mime_type mimeType,a.data_base64 dataBase64 FROM household_attachments a JOIN household_messages m ON m.id=a.entity_id AND m.household_id=a.household_id WHERE a.id=? AND a.household_id=? AND a.entity_type='message'`).bind(c.req.param("attachmentId"),a.householdId).first<{fileName:string;mimeType:string;dataBase64:string}>();if(!row)return apiError(c,404,"ATTACHMENT_NOT_FOUND","That attachment could not be found.");if(c.req.query("raw")==="1"){const bytes=decodeBase64(row.dataBase64);return new Response(bytes,{headers:{"content-type":row.mimeType,"content-disposition":`${row.mimeType.startsWith("image/")?"inline":"attachment"}; filename*=UTF-8''${encodeURIComponent(row.fileName)}`,"cache-control":"private, max-age=300","x-content-type-options":"nosniff"}})}return c.json(row)});

app.delete("/api/v1/households/:householdId/chat-attachments/:attachmentId",async c=>{const a=await access(c);if(a.response)return a.response;const row=await c.env.DB.prepare("SELECT uploaded_by uploadedBy FROM household_attachments WHERE id=? AND household_id=? AND entity_type='message'").bind(c.req.param("attachmentId"),a.householdId).first<{uploadedBy:string}>();if(!row)return apiError(c,404,"ATTACHMENT_NOT_FOUND","That attachment could not be found.");if(row.uploadedBy!==a.user.id)return apiError(c,403,"ATTACHMENT_OWNER_REQUIRED","You can only remove your own chat attachments.");await c.env.DB.prepare("DELETE FROM household_attachments WHERE id=? AND household_id=?").bind(c.req.param("attachmentId"),a.householdId).run();return c.json({ok:true})});

app.put("/api/v1/households/:householdId/messages/:id/reactions/:emoji",async c=>{const a=await access(c);if(a.response)return a.response;const emoji=decodeURIComponent(c.req.param("emoji"));if(!emoji||emoji.length>24)return apiError(c,400,"INVALID_REACTION","Choose a single emoji reaction.");const exists=await c.env.DB.prepare("SELECT 1 ok FROM household_messages WHERE id=? AND household_id=?").bind(c.req.param("id"),a.householdId).first();if(!exists)return apiError(c,404,"MESSAGE_NOT_FOUND","Message not found.");const input=await c.req.json().catch(()=>({})) as {active?:boolean};if(input.active===false)await c.env.DB.prepare("DELETE FROM household_message_reactions WHERE message_id=? AND user_id=? AND emoji=?").bind(c.req.param("id"),a.user.id,emoji).run();else await c.env.DB.prepare("INSERT OR IGNORE INTO household_message_reactions(message_id,user_id,emoji) VALUES(?,?,?)").bind(c.req.param("id"),a.user.id,emoji).run();return c.json({active:input.active!==false})});

export default app;
