import { Hono } from "hono";
import coreApp, { HouseholdRealtime } from "./index";
import everydayV2 from "./everyday-v2";
import familyHome from "./family-home";
import meals from "./meals";
import communication from "./communication";
import chatMedia from "./chat-media";
import familyTools from "./family-tools";
import feedback from "./feedback";
import gifSearch from "./gif-search";
import routines from "./routines";
import releaseState from "./release-state";
import { cancelAdminRelease, dispatchAdminRelease, fetchAdminReleaseStatus, requirePlatformAdmin } from "./admin";
import type { AppBindings } from "./http";

export { HouseholdRealtime };
const app = new Hono<AppBindings>();
app.get("/api/v1/admin/releases/status", async (c) => { const access = await requirePlatformAdmin(c); if (access.response) return access.response; return c.json(await fetchAdminReleaseStatus(c)); });
app.post("/api/v1/admin/releases", async (c) => { const access = await requirePlatformAdmin(c); if (access.response) return access.response; return dispatchAdminRelease(c); });
app.post("/api/v1/admin/releases/:runId/cancel", async (c) => { const access = await requirePlatformAdmin(c); if (access.response) return access.response; return cancelAdminRelease(c, Number(c.req.param("runId"))); });
app.route("/", releaseState);
app.route("/", feedback);
app.route("/", familyTools);
app.route("/", gifSearch);
app.route("/", chatMedia);
app.route("/", communication);
app.route("/", familyHome);
app.route("/", meals);
app.route("/", routines);
app.route("/", everydayV2);
app.route("/", coreApp);
export default app;
