import { Hono } from "hono";
import { createAuth } from "./auth";
import { apiError, type AppBindings } from "./http";

const app = new Hono<AppBindings>();
type Ctx = Parameters<typeof apiError>[0];
const languages=["en","nl","fr","de","es"] as const;
const attachmentTables:Record<string,string>={household:"households",note:"family_notes",meal:"meal_plans",recipe:"meal_recipes",message:"household_messages",task:"everyday_tasks",event:"everyday_events",poll:"household_polls"};
const allowedMimeTypes=new Set(["image/png","image/jpeg","image/webp","image/gif","application/pdf","text/plain"]);

async function user(c: Ctx) { const session=await createAuth(c.env,c.req.raw).api.getSession({headers:c.req.raw.headers}); return session?.user??null; }
async function member(c: Ctx,householdId:string,userId:string){return c.env.DB.prepare("SELECT 1 FROM memberships WHERE household_id=? AND user_id=? AND status='active'").bind(householdId,userId).first();}
async function requireMember(c: Ctx){const u=await user(c);if(!u)return{response:apiError(c,401,"AUTH_REQUIRED","Sign in to continue.")};const householdId=c.req.param("householdId")??"";if(!(await member(c,householdId,u.id)))return{response:apiError(c,403,"HOUSEHOLD_VIEW_REQUIRED","You do not have access to this household.")};return{u,householdId};}
function decodeBase64(value:string){const raw=atob(value);const bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);return bytes}
async function entityExists(c:Ctx,householdId:string,type:string,id:string|null){if(type==="household")return id===null||id===householdId;const table=attachmentTables[type];if(!table||!id)return false;return Boolean(await c.env.DB.prepare(`SELECT 1 FROM ${table} WHERE id=? AND household_id=? LIMIT 1`).bind(id,householdId).first())}

app.get("/api/v1/households/:householdId/family-tools",async c=>{const a=await requireMember(c);if(a.response)return a.response;const {u,householdId}=a;const [notifications,polls,attachments,locale,prefs]=await Promise.all([
 c.env.DB.prepare(`SELECT n.id,n.category,n.kind,n.title,n.body,n.entity_type entityType,n.entity_id entityId,n.direct,n.read_at readAt,n.created_at createdAt,u.name actorName FROM household_notifications n LEFT JOIN "user" u ON u.id=n.actor_user_id WHERE n.household_id=? AND n.user_id=? ORDER BY n.created_at DESC LIMIT 60`).bind(householdId,u.id).all(),
 c.env.DB.prepare(`SELECT p.id,p.question,p.multiple_choice multipleChoice,p.closes_at closesAt,p.created_at createdAt,u.name createdByName FROM household_polls p JOIN "user" u ON u.id=p.created_by WHERE p.household_id=? ORDER BY p.created_at DESC LIMIT 30`).bind(householdId).all(),
 c.env.DB.prepare(`SELECT a.id,a.entity_type entityType,a.entity_id entityId,a.file_name fileName,a.mime_type mimeType,a.size_bytes sizeBytes,a.created_at createdAt,u.name uploadedByName FROM household_attachments a JOIN "user" u ON u.id=a.uploaded_by WHERE a.household_id=? ORDER BY a.created_at DESC LIMIT 120`).bind(householdId).all(),
 c.env.DB.prepare("SELECT language,region,time_zone timeZone,offer_translations offerTranslations,translation_ttl_minutes translationTtlMinutes FROM user_locale_preferences WHERE user_id=?").bind(u.id).first(),
 c.env.DB.prepare("SELECT meals,polls,attachments FROM household_notification_preferences WHERE household_id=? AND user_id=?").bind(householdId,u.id).first(),]);
 const pollRows=[] as unknown[];for(const p of polls.results as Array<Record<string,unknown>>){const options=await c.env.DB.prepare(`SELECT o.id,o.label,COUNT(v.option_id) votes,EXISTS(SELECT 1 FROM household_poll_votes mine WHERE mine.poll_id=o.poll_id AND mine.option_id=o.id AND mine.user_id=?) votedByMe FROM household_poll_options o LEFT JOIN household_poll_votes v ON v.option_id=o.id WHERE o.poll_id=? GROUP BY o.id,o.label,o.position ORDER BY o.position`).bind(u.id,p.id).all();pollRows.push({...p,multipleChoice:Boolean(p.multipleChoice),options:options.results.map((o:any)=>({...o,votes:Number(o.votes),votedByMe:Boolean(o.votedByMe)}))});}
 const l:any=locale??{language:"en",region:"BE",timeZone:"Europe/Brussels",offerTranslations:1,translationTtlMinutes:5};return c.json({notifications:notifications.results.map((n:any)=>({...n,direct:Boolean(n.direct)})),polls:pollRows,attachments:attachments.results,locale:{...l,offerTranslations:Boolean(l.offerTranslations??1),translationTtlMinutes:Number(l.translationTtlMinutes??5)},preferences:{meals:Boolean((prefs as any)?.meals??1),polls:Boolean((prefs as any)?.polls??1),attachments:Boolean((prefs as any)?.attachments??0)}});
});
app.post("/api/v1/households/:householdId/notifications/read",async c=>{const a=await requireMember(c);if(a.response)return a.response;await c.env.DB.prepare("UPDATE household_notifications SET read_at=datetime('now') WHERE household_id=? AND user_id=? AND read_at IS NULL").bind(a.householdId,a.u.id).run();return c.json({ok:true});});
app.put("/api/v1/households/:householdId/family-tools/preferences",async c=>{const a=await requireMember(c);if(a.response)return a.response;const b=await c.req.json().catch(()=>null) as any;if(!b)return apiError(c,422,"VALIDATION_FAILED","Choose notification preferences.");await c.env.DB.prepare(`INSERT INTO household_notification_preferences(household_id,user_id,meals,polls,attachments) VALUES(?,?,?,?,?) ON CONFLICT(household_id,user_id) DO UPDATE SET meals=excluded.meals,polls=excluded.polls,attachments=excluded.attachments,updated_at=datetime('now')`).bind(a.householdId,a.u.id,b.meals?1:0,b.polls?1:0,b.attachments?1:0).run();return c.json({ok:true});});
app.put("/api/v1/households/:householdId/locale",async c=>{const a=await requireMember(c);if(a.response)return a.response;const b=await c.req.json().catch(()=>null) as any;if(!b||!languages.includes(b.language)||typeof b.region!=="string"||typeof b.timeZone!=="string")return apiError(c,422,"VALIDATION_FAILED","Check your language and region settings.");const ttl=[1,5,15,60].includes(Number(b.translationTtlMinutes))?Number(b.translationTtlMinutes):5;await c.env.DB.prepare(`INSERT INTO user_locale_preferences(user_id,language,region,time_zone,offer_translations,translation_ttl_minutes) VALUES(?,?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET language=excluded.language,region=excluded.region,time_zone=excluded.time_zone,offer_translations=excluded.offer_translations,translation_ttl_minutes=excluded.translation_ttl_minutes,updated_at=datetime('now')`).bind(a.u.id,b.language,b.region.trim().toUpperCase().slice(0,8),b.timeZone.trim().slice(0,80),b.offerTranslations===false?0:1,ttl).run();return c.json({language:b.language,region:b.region.trim().toUpperCase(),timeZone:b.timeZone.trim(),offerTranslations:b.offerTranslations!==false,translationTtlMinutes:ttl});});
app.post("/api/v1/households/:householdId/translate",async c=>{const a=await requireMember(c);if(a.response)return a.response;const b=await c.req.json().catch(()=>null) as any;const text=typeof b?.text==="string"?b.text.trim():"";const target=typeof b?.targetLanguage==="string"?b.targetLanguage:"";const source=typeof b?.sourceLanguage==="string"?b.sourceLanguage:"auto";if(!text||text.length>5000||!languages.includes(target as any)||(source!=="auto"&&!languages.includes(source as any)))return apiError(c,422,"VALIDATION_FAILED","Choose valid text and a translation language.");if(source==="auto")return apiError(c,422,"SOURCE_LANGUAGE_REQUIRED","Choose the language the family content was written in.");try{const result:any=await c.env.AI.run("@cf/meta/m2m100-1.2b",{text,source_lang:source,target_lang:target});const translated=String(result?.translated_text??result?.translation??"").trim();if(!translated)return apiError(c,500,"TRANSLATION_FAILED","Kit Hub could not translate that yet.");const pref:any=await c.env.DB.prepare("SELECT translation_ttl_minutes ttl FROM user_locale_preferences WHERE user_id=?").bind(a.u.id).first();const ttl=Number(pref?.ttl??5);return c.json({translatedText:translated,sourceLanguage:source,targetLanguage:target,visibleForMinutes:ttl,expiresAt:new Date(Date.now()+ttl*60000).toISOString(),viewerOnly:true});}catch{return apiError(c,500,"TRANSLATION_FAILED","Kit Hub could not translate that yet.");}});
app.post("/api/v1/households/:householdId/polls",async c=>{const a=await requireMember(c);if(a.response)return a.response;const b=await c.req.json().catch(()=>null) as any;const question=typeof b?.question==="string"?b.question.trim():"";const options=Array.isArray(b?.options)?b.options.map((x:unknown)=>typeof x==="string"?x.trim():"").filter(Boolean):[];if(!question||question.length>240||options.length<2||options.length>8)return apiError(c,422,"VALIDATION_FAILED","Add a question and 2 to 8 choices.");const id=crypto.randomUUID();await c.env.DB.batch([c.env.DB.prepare("INSERT INTO household_polls(id,household_id,question,multiple_choice,closes_at,created_by) VALUES(?,?,?,?,?,?)").bind(id,a.householdId,question,b.multipleChoice?1:0,b.closesAt||null,a.u.id),...options.map((label:string,i:number)=>c.env.DB.prepare("INSERT INTO household_poll_options(id,poll_id,label,position) VALUES(?,?,?,?)").bind(crypto.randomUUID(),id,label,i))]);return c.json({id},201);});
app.put("/api/v1/households/:householdId/polls/:pollId/vote",async c=>{const a=await requireMember(c);if(a.response)return a.response;const b=await c.req.json().catch(()=>null) as any;const ids=Array.isArray(b?.optionIds)?b.optionIds.filter((x:unknown)=>typeof x==="string"):[];const poll=await c.env.DB.prepare("SELECT multiple_choice multipleChoice,closes_at closesAt,closed_at closedAt FROM household_polls WHERE id=? AND household_id=?").bind(c.req.param("pollId"),a.householdId).first<any>();if(!poll)return apiError(c,404,"POLL_NOT_FOUND","That poll could not be found.");if(poll.closedAt||(poll.closesAt&&new Date(poll.closesAt)<=new Date()))return apiError(c,409,"POLL_CLOSED","This poll is closed.");if(!poll.multipleChoice&&ids.length>1)return apiError(c,422,"VALIDATION_FAILED","Choose one option.");const valid=await c.env.DB.prepare(`SELECT id FROM household_poll_options WHERE poll_id=?`).bind(c.req.param("pollId")).all<{id:string}>();const set=new Set(valid.results.map(x=>x.id));if(ids.some((id:string)=>!set.has(id)))return apiError(c,422,"VALIDATION_FAILED","Choose an option from this poll.");await c.env.DB.batch([c.env.DB.prepare("DELETE FROM household_poll_votes WHERE poll_id=? AND user_id=?").bind(c.req.param("pollId"),a.u.id),...ids.map((id:string)=>c.env.DB.prepare("INSERT INTO household_poll_votes(poll_id,option_id,user_id) VALUES(?,?,?)").bind(c.req.param("pollId"),id,a.u.id))]);return c.json({ok:true});});
app.post("/api/v1/households/:householdId/attachments",async c=>{const a=await requireMember(c);if(a.response)return a.response;const b=await c.req.json().catch(()=>null) as any;const entityType=typeof b?.entityType==="string"?b.entityType:"household",entityId=typeof b?.entityId==="string"&&b.entityId?b.entityId:null;if(!b||typeof b.fileName!=="string"||typeof b.mimeType!=="string"||typeof b.dataBase64!=="string"||!attachmentTables[entityType])return apiError(c,422,"VALIDATION_FAILED","Choose a valid file.");if(!allowedMimeTypes.has(b.mimeType))return apiError(c,422,"FILE_TYPE_NOT_ALLOWED","Use PNG, JPG, WebP, GIF, PDF or text files.");if(!(await entityExists(c,a.householdId,entityType,entityId)))return apiError(c,404,"ATTACHMENT_TARGET_NOT_FOUND","That item could not be found in this household.");const count=await c.env.DB.prepare("SELECT COUNT(*) count FROM household_attachments WHERE household_id=? AND entity_type=? AND COALESCE(entity_id,'')=COALESCE(?, '')").bind(a.householdId,entityType,entityId).first<{count:number}>();if(Number(count?.count??0)>=3)return apiError(c,422,"ATTACHMENT_LIMIT","Each item can have up to 3 attachments.");const size=Math.floor(b.dataBase64.length*3/4);if(size<1||size>1572864)return apiError(c,422,"FILE_TOO_LARGE","Files can be up to 1.5 MB each.");const id=crypto.randomUUID();await c.env.DB.prepare("INSERT INTO household_attachments(id,household_id,uploaded_by,entity_type,entity_id,file_name,mime_type,size_bytes,data_base64) VALUES(?,?,?,?,?,?,?,?,?)").bind(id,a.householdId,a.u.id,entityType,entityId,b.fileName.slice(0,180),b.mimeType,size,b.dataBase64).run();return c.json({id,entityType,entityId,fileName:b.fileName,mimeType:b.mimeType,sizeBytes:size,uploadedByName:a.u.name,createdAt:new Date().toISOString()},201);});
app.get("/api/v1/households/:householdId/attachments/:attachmentId",async c=>{const a=await requireMember(c);if(a.response)return a.response;const row=await c.env.DB.prepare("SELECT id,uploaded_by uploadedBy,entity_type entityType,entity_id entityId,file_name fileName,mime_type mimeType,size_bytes sizeBytes,data_base64 dataBase64,created_at createdAt FROM household_attachments WHERE id=? AND household_id=?").bind(c.req.param("attachmentId"),a.householdId).first<{id:string;uploadedBy:string;entityType:string;entityId:string|null;fileName:string;mimeType:string;sizeBytes:number;dataBase64:string;createdAt:string}>();if(!row)return apiError(c,404,"ATTACHMENT_NOT_FOUND","That attachment could not be found.");if(c.req.query("raw")==="1"){const bytes=decodeBase64(row.dataBase64);return new Response(bytes,{headers:{"content-type":row.mimeType,"content-disposition":`${row.mimeType.startsWith("image/")?"inline":"attachment"}; filename*=UTF-8''${encodeURIComponent(row.fileName)}`,"cache-control":"private, max-age=300","x-content-type-options":"nosniff"}})}return c.json(row);});
app.delete("/api/v1/households/:householdId/attachments/:attachmentId",async c=>{const a=await requireMember(c);if(a.response)return a.response;const row=await c.env.DB.prepare("SELECT uploaded_by uploadedBy FROM household_attachments WHERE id=? AND household_id=?").bind(c.req.param("attachmentId"),a.householdId).first<{uploadedBy:string}>();if(!row)return apiError(c,404,"ATTACHMENT_NOT_FOUND","That attachment could not be found.");if(row.uploadedBy!==a.u.id)return apiError(c,403,"ATTACHMENT_OWNER_REQUIRED","You can only remove files you uploaded.");await c.env.DB.prepare("DELETE FROM household_attachments WHERE id=? AND household_id=?").bind(c.req.param("attachmentId"),a.householdId).run();return c.json({ok:true});});
export default app;