import { Hono } from "hono";
import { createAuth } from "./auth";
import { apiError, type AppBindings } from "./http";

const app = new Hono<AppBindings>();
type Ctx = Parameters<typeof apiError>[0];

async function currentUser(c:Ctx){const session=await createAuth(c.env,c.req.raw).api.getSession({headers:c.req.raw.headers});return session?.user??null;}
async function member(c:Ctx,householdId:string,userId:string){return c.env.DB.prepare("SELECT 1 FROM memberships WHERE household_id=? AND user_id=? AND status='active'").bind(householdId,userId).first();}
async function requireMember(c:Ctx){const user=await currentUser(c);if(!user)return{response:apiError(c,401,"AUTH_REQUIRED","Sign in to continue.")};const householdId=c.req.param("householdId");if(!(await member(c,householdId,user.id)))return{response:apiError(c,403,"HOUSEHOLD_VIEW_REQUIRED","You do not have access to this household.")};return{user,householdId};}
function parseAudience(value:unknown){if(!Array.isArray(value))return[] as string[];return Array.from(new Set(value.filter((item):item is string=>typeof item==="string"&&item.length>0))).slice(0,50);}
async function validateAudience(c:Ctx,householdId:string,userId:string,ids:string[]){const filtered=ids.filter(id=>id!==userId);if(!filtered.length)return filtered;const placeholders=filtered.map(()=>"?").join(",");const rows=await c.env.DB.prepare(`SELECT user_id userId FROM memberships WHERE household_id=? AND status='active' AND user_id IN (${placeholders})`).bind(householdId,...filtered).all<{userId:string}>();if(rows.results.length!==filtered.length)return null;return filtered;}
function expiryFromMinutes(minutes:number,maxMinutes:number){const safe=Math.max(15,Math.min(maxMinutes,Math.round(minutes)));return new Date(Date.now()+safe*60000).toISOString();}
function isActive(value:string|null|undefined){return Boolean(value&&new Date(value).getTime()>Date.now());}
function canSee(raw:string|null|undefined,viewerId:string,ownerId:string){if(viewerId===ownerId)return true;try{const ids=JSON.parse(raw||"[]");return Array.isArray(ids)&&ids.includes(viewerId)}catch{return false}}
function publicRow(row:any,viewerId:string){const own=row.userId===viewerId;const statusVisible=own||(isActive(row.statusExpiresAt)&&canSee(row.statusVisibleTo,viewerId,row.userId));const locationVisible=own||(isActive(row.locationExpiresAt)&&canSee(row.locationVisibleTo,viewerId,row.userId));return{userId:row.userId,name:row.name,status:statusVisible&&isActive(row.statusExpiresAt)?row.statusText:null,statusExpiresAt:statusVisible&&isActive(row.statusExpiresAt)?row.statusExpiresAt:null,location:locationVisible&&isActive(row.locationExpiresAt)&&Number.isFinite(Number(row.latitude))&&Number.isFinite(Number(row.longitude))?{latitude:Number(row.latitude),longitude:Number(row.longitude),accuracy:row.locationAccuracy,expiresAt:row.locationExpiresAt}:null,updatedAt:row.updatedAt,own};}

app.get("/api/v1/households/:householdId/presence",async c=>{const access=await requireMember(c);if(access.response)return access.response;const rows=await c.env.DB.prepare(`SELECT m.user_id userId,u.name,p.status_text statusText,p.status_expires_at statusExpiresAt,p.status_visible_to statusVisibleTo,p.latitude,p.longitude,p.location_accuracy locationAccuracy,p.location_expires_at locationExpiresAt,p.location_visible_to locationVisibleTo,p.updated_at updatedAt FROM memberships m JOIN "user" u ON u.id=m.user_id LEFT JOIN household_presence p ON p.household_id=m.household_id AND p.user_id=m.user_id WHERE m.household_id=? AND m.status='active' ORDER BY u.name`).bind(access.householdId).all<any>();const own=rows.results.find((row:any)=>row.userId===access.user.id);return c.json({members:rows.results.map((row:any)=>({userId:row.userId,name:row.name})),presence:rows.results.map((row:any)=>publicRow(row,access.user.id)),settings:own?{status:own.statusText??"",statusExpiresAt:own.statusExpiresAt??null,statusVisibleTo:JSON.parse(own.statusVisibleTo||"[]"),locationActive:isActive(own.locationExpiresAt),locationAccuracy:own.locationAccuracy??"approximate",locationExpiresAt:own.locationExpiresAt??null,locationVisibleTo:JSON.parse(own.locationVisibleTo||"[]")}:{status:"",statusExpiresAt:null,statusVisibleTo:[],locationActive:false,locationAccuracy:"approximate",locationExpiresAt:null,locationVisibleTo:[]}});});

app.put("/api/v1/households/:householdId/presence/status",async c=>{const access=await requireMember(c);if(access.response)return access.response;const body=await c.req.json().catch(()=>null) as any;const text=typeof body?.status==="string"?body.status.trim().slice(0,120):"";if(!text)return apiError(c,422,"STATUS_REQUIRED","Add a short status before sharing it.");const audience=await validateAudience(c,access.householdId,access.user.id,parseAudience(body?.visibleTo));if(audience===null)return apiError(c,422,"INVALID_AUDIENCE","Choose household members who can see your status.");if(!audience.length)return apiError(c,422,"AUDIENCE_REQUIRED","Choose at least one household member who can see your status.");const expiresAt=expiryFromMinutes(Number(body?.durationMinutes)||240,10080);await c.env.DB.prepare(`INSERT INTO household_presence(household_id,user_id,status_text,status_expires_at,status_visible_to) VALUES(?,?,?,?,?) ON CONFLICT(household_id,user_id) DO UPDATE SET status_text=excluded.status_text,status_expires_at=excluded.status_expires_at,status_visible_to=excluded.status_visible_to,updated_at=datetime('now')`).bind(access.householdId,access.user.id,text,expiresAt,JSON.stringify(audience)).run();return c.json({ok:true,expiresAt});});

app.put("/api/v1/households/:householdId/presence/location",async c=>{const access=await requireMember(c);if(access.response)return access.response;const body=await c.req.json().catch(()=>null) as any;const latitude=Number(body?.latitude),longitude=Number(body?.longitude);if(!Number.isFinite(latitude)||latitude< -90||latitude>90||!Number.isFinite(longitude)||longitude< -180||longitude>180)return apiError(c,422,"INVALID_LOCATION","Kit Hub could not read that location.");const accuracy=body?.accuracy==="precise"?"precise":"approximate";const audience=await validateAudience(c,access.householdId,access.user.id,parseAudience(body?.visibleTo));if(audience===null)return apiError(c,422,"INVALID_AUDIENCE","Choose household members who can see your location.");if(!audience.length)return apiError(c,422,"AUDIENCE_REQUIRED","Choose at least one household member who can see your location.");const expiresAt=expiryFromMinutes(Number(body?.durationMinutes)||60,1440);const storedLat=accuracy==="approximate"?Math.round(latitude*100)/100:Math.round(latitude*100000)/100000;const storedLon=accuracy==="approximate"?Math.round(longitude*100)/100:Math.round(longitude*100000)/100000;await c.env.DB.prepare(`INSERT INTO household_presence(household_id,user_id,latitude,longitude,location_accuracy,location_expires_at,location_visible_to) VALUES(?,?,?,?,?,?,?) ON CONFLICT(household_id,user_id) DO UPDATE SET latitude=excluded.latitude,longitude=excluded.longitude,location_accuracy=excluded.location_accuracy,location_expires_at=excluded.location_expires_at,location_visible_to=excluded.location_visible_to,updated_at=datetime('now')`).bind(access.householdId,access.user.id,storedLat,storedLon,accuracy,expiresAt,JSON.stringify(audience)).run();return c.json({ok:true,expiresAt,accuracy});});

app.post("/api/v1/households/:householdId/presence/stop",async c=>{const access=await requireMember(c);if(access.response)return access.response;const body=await c.req.json().catch(()=>null) as any;const kind=body?.kind==="status"?"status":body?.kind==="location"?"location":"all";if(kind==="status"||kind==="all")await c.env.DB.prepare("UPDATE household_presence SET status_text=NULL,status_expires_at=NULL,status_visible_to='[]',updated_at=datetime('now') WHERE household_id=? AND user_id=?").bind(access.householdId,access.user.id).run();if(kind==="location"||kind==="all")await c.env.DB.prepare("UPDATE household_presence SET latitude=NULL,longitude=NULL,location_accuracy=NULL,location_expires_at=NULL,location_visible_to='[]',updated_at=datetime('now') WHERE household_id=? AND user_id=?").bind(access.householdId,access.user.id).run();return c.json({ok:true});});

export default app;
