import { Hono } from "hono";
import { createAuth } from "./auth";
import { recordHouseholdActivity } from "./activity";
import { apiError, type AppBindings } from "./http";

const app=new Hono<AppBindings>();
type Ctx=Parameters<typeof apiError>[0];
async function access(c:Ctx){const session=await createAuth(c.env,c.req.raw).api.getSession({headers:c.req.raw.headers});if(!session?.user)return{response:apiError(c,401,"AUTH_REQUIRED","Sign in to continue.")};const householdId=c.req.param("householdId");const member=await c.env.DB.prepare("SELECT role_key role FROM memberships WHERE household_id=? AND user_id=? AND status='active'").bind(householdId,session.user.id).first<{role:string}>();if(!member)return{response:apiError(c,403,"HOUSEHOLD_VIEW_REQUIRED","You do not have access to this household.")};return{user:session.user,householdId,canManage:["owner","admin","adult","teen"].includes(member.role)}}
function nextDue(current:string|null,cadence:string){const d=current?new Date(current):new Date();if(Number.isNaN(d.getTime()))return null;if(cadence==="daily")d.setDate(d.getDate()+1);else if(cadence==="monthly")d.setMonth(d.getMonth()+1);else d.setDate(d.getDate()+7);return d.toISOString()}
app.get("/api/v1/households/:householdId/routines",async c=>{const a=await access(c);if(a.response)return a.response;const [routines,members,recent]=await Promise.all([c.env.DB.prepare(`SELECT r.id,r.title,r.notes,r.cadence,r.assignee_user_id assigneeUserId,u.name assigneeName,r.next_due_at nextDueAt,r.reminder_minutes reminderMinutes,r.active,r.created_at createdAt,(SELECT MAX(completed_at) FROM household_routine_completions x WHERE x.routine_id=r.id) lastCompletedAt FROM household_routines r LEFT JOIN "user" u ON u.id=r.assignee_user_id WHERE r.household_id=? AND r.active=1 ORDER BY CASE WHEN r.next_due_at IS NULL THEN 1 ELSE 0 END,r.next_due_at,r.title`).bind(a.householdId).all(),c.env.DB.prepare(`SELECT m.user_id userId,u.name FROM memberships m JOIN "user" u ON u.id=m.user_id WHERE m.household_id=? AND m.status='active' ORDER BY u.name`).bind(a.householdId).all(),c.env.DB.prepare(`SELECT x.id,r.title,u.name completedByName,x.completed_at completedAt FROM household_routine_completions x JOIN household_routines r ON r.id=x.routine_id JOIN "user" u ON u.id=x.completed_by WHERE x.household_id=? ORDER BY x.completed_at DESC LIMIT 8`).bind(a.householdId).all()]);return c.json({routines:routines.results.map((r:any)=>({...r,active:Boolean(r.active)})),members:members.results,recent:recent.results,canManage:a.canManage})});
app.post("/api/v1/households/:householdId/routines",async c=>{const a=await access(c);if(a.response)return a.response;if(!a.canManage)return apiError(c,403,"ROUTINES_MANAGE_REQUIRED","You do not have permission to manage routines.");const b=await c.req.json().catch(()=>null) as any;const title=typeof b?.title==="string"?b.title.trim():"";const cadence=["daily","weekly","monthly"].includes(b?.cadence)?b.cadence:"weekly";if(!title||title.length>160)return apiError(c,422,"VALIDATION_FAILED","Routine title must be between 1 and 160 characters.");let assignee:string|null=typeof b?.assigneeUserId==="string"&&b.assigneeUserId?b.assigneeUserId:null;if(assignee){const m=await c.env.DB.prepare("SELECT 1 FROM memberships WHERE household_id=? AND user_id=? AND status='active'").bind(a.householdId,assignee).first();if(!m)return apiError(c,422,"ASSIGNEE_NOT_MEMBER","Choose an active household member.")}const due=typeof b?.nextDueAt==="string"&&b.nextDueAt&&!Number.isNaN(Date.parse(b.nextDueAt))?new Date(b.nextDueAt).toISOString():null;const reminder=typeof b?.reminderMinutes==="number"?Math.max(0,Math.min(10080,b.reminderMinutes)):null;const id=crypto.randomUUID();await c.env.DB.prepare("INSERT INTO household_routines(id,household_id,title,notes,cadence,assignee_user_id,next_due_at,reminder_minutes,created_by) VALUES(?,?,?,?,?,?,?,?,?)").bind(id,a.householdId,title,typeof b?.notes==="string"?b.notes.trim().slice(0,1200)||null:null,cadence,assignee,due,reminder,a.user.id).run();await recordHouseholdActivity(c,a.householdId,a.user.id,"routine.add",`${a.user.name} added routine “${title}”.`);return c.json({id},201)});
app.post("/api/v1/households/:householdId/routines/:routineId/complete",async c=>{const a=await access(c);if(a.response)return a.response;const routine=await c.env.DB.prepare("SELECT id,title,cadence,next_due_at nextDueAt,assignee_user_id assigneeUserId FROM household_routines WHERE id=? AND household_id=? AND active=1").bind(c.req.param("routineId"),a.householdId).first<any>();if(!routine)return apiError(c,404,"ROUTINE_NOT_FOUND","That routine could not be found.");if(routine.assigneeUserId&&routine.assigneeUserId!==a.user.id&&!a.canManage)return apiError(c,403,"ROUTINE_ASSIGNEE_REQUIRED","This routine is assigned to another household member.");await c.env.DB.batch([c.env.DB.prepare("INSERT INTO household_routine_completions(id,routine_id,household_id,completed_by) VALUES(?,?,?,?)").bind(crypto.randomUUID(),routine.id,a.householdId,a.user.id),c.env.DB.prepare("UPDATE household_routines SET next_due_at=?,updated_at=datetime('now') WHERE id=?").bind(nextDue(routine.nextDueAt,routine.cadence),routine.id)]);await recordHouseholdActivity(c,a.householdId,a.user.id,"routine.completed",`${a.user.name} completed “${routine.title}”.`);return c.json({ok:true})});
app.delete("/api/v1/households/:householdId/routines/:routineId",async c=>{const a=await access(c);if(a.response)return a.response;if(!a.canManage)return apiError(c,403,"ROUTINES_MANAGE_REQUIRED","You do not have permission to manage routines.");const result=await c.env.DB.prepare("UPDATE household_routines SET active=0,updated_at=datetime('now') WHERE id=? AND household_id=?").bind(c.req.param("routineId"),a.householdId).run();if(!result.meta.changes)return apiError(c,404,"ROUTINE_NOT_FOUND","That routine could not be found.");return c.json({deleted:true})});
export default app;
