import { Hono } from "hono";
import { createAuth } from "./auth";
import { apiError, type AppBindings } from "./http";

const app=new Hono<AppBindings>();
type Ctx=Parameters<typeof apiError>[0];
type Access={user:{id:string};householdId:string}|{response:ReturnType<typeof apiError>};
type Meal={id:string;mealDate:string;mealType:string;title:string};
function clean(v:unknown,max=180){return typeof v==="string"?v.trim().slice(0,max):""}
function norm(v:string){return v.toLowerCase().replace(/[^a-z0-9]+/g," ").trim()}
async function access(c:Ctx):Promise<Access>{const session=await createAuth(c.env,c.req.raw).api.getSession({headers:c.req.raw.headers});if(!session?.user)return{response:apiError(c,401,"AUTH_REQUIRED","Sign in to ask Silvi about meals.")};const householdId=c.req.param("householdId")??"";const m=householdId?await c.env.DB.prepare("SELECT 1 FROM memberships WHERE household_id=? AND user_id=? AND status='active'").bind(householdId,session.user.id).first():null;if(!m)return{response:apiError(c,403,"HOUSEHOLD_VIEW_REQUIRED","You do not have access to this household.")};return{user:session.user,householdId}}
async function canManage(c:Ctx,h:string,u:string){const m=await c.env.DB.prepare("SELECT role_key role FROM memberships WHERE household_id=? AND user_id=? AND status='active'").bind(h,u).first<{role:string}>();if(!m)return false;const o=await c.env.DB.prepare("SELECT effect FROM member_permission_overrides WHERE household_id=? AND user_id=? AND permission_key='meals.manage' LIMIT 1").bind(h,u).first<{effect:string}>();if(o)return o.effect==="allow";const p=await c.env.DB.prepare("SELECT effect FROM role_permissions WHERE role_key=? AND permission_key='meals.manage' LIMIT 1").bind(m.role).first<{effect:string}>();return p?.effect==="allow"}
async function timeZone(c:Ctx,h:string,u:string){const [l,hh]=await Promise.all([c.env.DB.prepare("SELECT time_zone timeZone FROM user_locale_preferences WHERE user_id=?").bind(u).first<{timeZone:string}>(),c.env.DB.prepare("SELECT timezone FROM households WHERE id=?").bind(h).first<{timezone:string}>()]);return l?.timeZone||hh?.timezone||"UTC"}
function localYmd(offset:number,tz:string){const d=new Date(Date.now()+offset*86400000);const parts=new Intl.DateTimeFormat("en-CA",{timeZone:tz,year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(d);const get=(t:string)=>parts.find(p=>p.type===t)?.value||"";return `${get("year")}-${get("month")}-${get("day")}`}
function parseMeal(q:string){if(!/(?:we(?:'re| are)? (?:going to )?(?:eat|have)|we(?:'ll| will) (?:eat|have)|(?:eat|have) .* (?:tomorrow|tonight)|(?:tomorrow|tonight|today)\s+we\s+(?:eat|have)|dinner .* (?:tomorrow|tonight))/i.test(q))return null;const offset=/\btomorrow\b/i.test(q)?1:0;const mealType=/\bbreakfast\b/i.test(q)?"breakfast":/\blunch\b/i.test(q)?"lunch":/\bsnack\b/i.test(q)?"snack":"dinner";let title=q.replace(/\b(?:tomorrow|tonight|today)\b/ig,"").trim();title=title.replace(/^(?:we(?:'re| are)? (?:going to )?(?:eat|have)|we(?:'ll| will) (?:eat|have)|we\s+(?:eat|have)|(?:for )?(?:breakfast|lunch|dinner|snack) (?:we(?:'re| are)? (?:going to )?(?:eat|have) )?)/i,"").replace(/[.!?]+$/g,"").trim();title=title.replace(/^(?:some|a|an|the)\s+/i,"").trim();if(!title||title.length>120||/^(something|food|dinner)$/i.test(title))return null;return{title,mealType,offset}}
function similar(a:string,b:string){const x=norm(a),y=norm(b);return x===y||x.includes(y)||y.includes(x)}
app.post("/api/v1/households/:householdId/silvi/ask",async(c,next)=>{const body=await c.req.json().catch(()=>null) as {question?:unknown}|null;const question=clean(body?.question,700),parsed=parseMeal(question);if(!parsed)return next();const a=await access(c);if("response" in a)return a.response;const tz=await timeZone(c,a.householdId,a.user.id),mealDate=localYmd(parsed.offset,tz);const rows=await c.env.DB.prepare("SELECT id,meal_date mealDate,meal_type mealType,title FROM meal_plans WHERE household_id=? AND meal_date=? ORDER BY meal_type").bind(a.householdId,mealDate).all<Meal>();const same=rows.results.find(m=>similar(m.title,parsed.title));if(same)return c.json({answer:`“${same.title}” is already planned for ${same.mealType} on ${mealDate}, so I won't add it again.`,followUps:["Show me that day's meal plan","What else is planned tomorrow?"],generatedAt:new Date().toISOString(),requiresConfirmation:false,source:"kit-hub"});const occupied=rows.results.find(m=>m.mealType===parsed.mealType);if(occupied)return c.json({answer:`${parsed.mealType[0]!.toUpperCase()+parsed.mealType.slice(1)} on ${mealDate} already has “${occupied.title}” planned. Do you want to replace it with “${parsed.title}”?`,followUps:[`Replace ${occupied.title} with ${parsed.title} for ${parsed.mealType} on ${mealDate}`,"Keep the existing meal","Show me that day's meal plan"],generatedAt:new Date().toISOString(),requiresConfirmation:false,source:"kit-hub"});if(!(await canManage(c,a.householdId,a.user.id)))return c.json({answer:`“${parsed.title}” isn't planned yet, but you don't currently have permission to change the household meal plan.`,followUps:["Show me the meal plan"],generatedAt:new Date().toISOString(),requiresConfirmation:false,source:"kit-hub"});const id=crypto.randomUUID(),expiresAt=new Date(Date.now()+10*60*1000).toISOString(),payload={mealDate,mealType:parsed.mealType,title:parsed.title},summary=`Plan “${parsed.title}” for ${parsed.mealType} on ${mealDate}.`;await c.env.DB.prepare("INSERT INTO silvi_action_proposals(id,household_id,user_id,action_type,summary,payload_json,expires_at) VALUES(?,?,?,?,?,?,?)").bind(id,a.householdId,a.user.id,"meal.plan",summary,JSON.stringify(payload),expiresAt).run();return c.json({answer:`I checked the meal plan first. Nothing matching “${parsed.title}” is planned for ${mealDate}, so I can add it as ${parsed.mealType} after you approve the change below.`,proposal:{id,type:"meal.plan",summary,payload,expiresAt},followUps:["Show me that day's meal plan"],generatedAt:new Date().toISOString(),requiresConfirmation:true,source:"kit-hub"})});
export default app;
