import { Hono } from "hono";
import { createAuth } from "./auth";
import { apiError, type AppBindings } from "./http";

const app=new Hono<AppBindings>();
type Ctx=Parameters<typeof apiError>[0];
type Authorized={user:{id:string};householdId:string};
type Access=Authorized|{response:ReturnType<typeof apiError>};
type Meal={id:string;mealDate:string;mealType:string;title:string};
function clean(v:unknown,max=180){return typeof v==="string"?v.trim().slice(0,max):""}
function norm(v:string){return v.toLowerCase().replace(/[^a-z0-9]+/g," ").trim()}
async function access(c:Ctx):Promise<Access>{const session=await createAuth(c.env,c.req.raw).api.getSession({headers:c.req.raw.headers});if(!session?.user)return{response:apiError(c,401,"AUTH_REQUIRED","Sign in to ask Silvi about meals.")};const householdId=c.req.param("householdId")??"";const m=householdId?await c.env.DB.prepare("SELECT 1 FROM memberships WHERE household_id=? AND user_id=? AND status='active'").bind(householdId,session.user.id).first():null;if(!m)return{response:apiError(c,403,"HOUSEHOLD_VIEW_REQUIRED","You do not have access to this household.")};return{user:session.user,householdId}}
async function canManage(c:Ctx,h:string,u:string){const m=await c.env.DB.prepare("SELECT role_key role FROM memberships WHERE household_id=? AND user_id=? AND status='active'").bind(h,u).first<{role:string}>();if(!m)return false;const o=await c.env.DB.prepare("SELECT effect FROM member_permission_overrides WHERE household_id=? AND user_id=? AND permission_key='meals.manage' LIMIT 1").bind(h,u).first<{effect:string}>();if(o)return o.effect==="allow";const p=await c.env.DB.prepare("SELECT effect FROM role_permissions WHERE role_key=? AND permission_key='meals.manage' LIMIT 1").bind(m.role).first<{effect:string}>();return p?.effect==="allow"}
async function timeZone(c:Ctx,h:string,u:string){const [l,hh]=await Promise.all([c.env.DB.prepare("SELECT time_zone timeZone FROM user_locale_preferences WHERE user_id=?").bind(u).first<{timeZone:string}>(),c.env.DB.prepare("SELECT timezone FROM households WHERE id=?").bind(h).first<{timezone:string}>()]);return l?.timeZone||hh?.timezone||"UTC"}
function localYmd(offset:number,tz:string){const d=new Date(Date.now()+offset*86400000);const parts=new Intl.DateTimeFormat("en-CA",{timeZone:tz,year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(d);const get=(t:string)=>parts.find(p=>p.type===t)?.value||"";return `${get("year")}-${get("month")}-${get("day")}`}
function weekdayOffset(name:string,tz:string){const days=["sun","mon","tue","wed","thu","fri","sat"];const target=days.findIndex(x=>name.toLowerCase().startsWith(x));if(target<0)return null;const current=days.indexOf(new Intl.DateTimeFormat("en-US",{timeZone:tz,weekday:"short"}).format(new Date()).slice(0,3).toLowerCase());let delta=(target-current+7)%7;if(delta===0)delta=7;return delta}
function parseMeal(q:string){const lower=q.toLowerCase();if(!/(?:we(?:'re| are)? (?:going to )?(?:eat|have)|we(?:'ll| will) (?:eat|have)|(?:eat|have) .+|(?:breakfast|lunch|dinner|snack) .+)/i.test(q))return null;const hasDate=/\b(tomorrow|tonight|today|monday|tuesday|wednesday|thursday|friday|saturday|sunday)\b/i.test(q),explicitMealType=/\b(breakfast|lunch|dinner|snack)\b/i.test(q);const offset=/\btomorrow\b/i.test(q)?1:0;const mealType=/\bbreakfast\b/i.test(q)?"breakfast":/\blunch\b/i.test(q)?"lunch":/\bsnack\b/i.test(q)?"snack":/\bdinner\b/i.test(q)?"dinner":"";let title=q.replace(/\b(?:tomorrow|tonight|today|monday|tuesday|wednesday|thursday|friday|saturday|sunday)\b/ig,"").replace(/^(?:we(?:'re| are)? (?:going to )?(?:eat|have)|we(?:'ll| will) (?:eat|have)|we\s+(?:eat|have)|(?:for )?(?:breakfast|lunch|dinner|snack) (?:we(?:'re| are)? (?:going to )?(?:eat|have) )?)/i,"").replace(/\b(?:for|as)\s+(?:breakfast|lunch|dinner|snack)\b/ig,"").replace(/[.!?]+$/g,"").trim();title=title.replace(/^(?:some|a|an|the)\s+/i,"").trim();if(!title||title.length>120||/^(something|food|dinner|lunch|breakfast|snack)$/i.test(title))return null;const weekday=lower.match(/\b(monday|tuesday|wednesday|thursday|friday|saturday|sunday)\b/i)?.[1]??null;return{title,mealType,offset,hasDate,weekday,explicitMealType}}
function similar(a:string,b:string){const x=norm(a),y=norm(b);return x===y||x.includes(y)||y.includes(x)}
async function remember(c:Ctx,h:string,u:string,kind:string,payload:Record<string,unknown>){await c.env.DB.prepare("INSERT INTO silvi_clarification_state(household_id,user_id,kind,payload_json,expires_at) VALUES(?,?,?,?,?) ON CONFLICT(household_id,user_id) DO UPDATE SET kind=excluded.kind,payload_json=excluded.payload_json,expires_at=excluded.expires_at,created_at=datetime('now')").bind(h,u,kind,JSON.stringify(payload),new Date(Date.now()+10*60000).toISOString()).run()}
async function clearMemory(c:Ctx,h:string,u:string){await c.env.DB.prepare("DELETE FROM silvi_clarification_state WHERE household_id=? AND user_id=?").bind(h,u).run()}
async function makeProposal(c:Ctx,a:Authorized,mealDate:string,mealType:string,title:string){const id=crypto.randomUUID(),expiresAt=new Date(Date.now()+10*60*1000).toISOString(),payload={mealDate,mealType,title},summary=`Plan “${title}” for ${mealType} on ${mealDate}.`;await c.env.DB.prepare("INSERT INTO silvi_action_proposals(id,household_id,user_id,action_type,summary,payload_json,expires_at) VALUES(?,?,?,?,?,?,?)").bind(id,a.householdId,a.user.id,"meal.plan",summary,JSON.stringify(payload),expiresAt).run();return{id,type:"meal.plan",summary,payload,expiresAt}}
async function planReply(c:Ctx,a:Authorized,mealDate:string,mealType:string,title:string){const rows=await c.env.DB.prepare("SELECT id,meal_date mealDate,meal_type mealType,title FROM meal_plans WHERE household_id=? AND meal_date=? ORDER BY meal_type").bind(a.householdId,mealDate).all<Meal>();const same=rows.results.find(m=>similar(m.title,title));if(same)return c.json({answer:`“${same.title}” is already planned for ${same.mealType} on ${mealDate}, so I won't add it again.`,followUps:["Show me that day's meal plan","What else is planned that day?"],generatedAt:new Date().toISOString(),requiresConfirmation:false,source:"kit-hub"});const occupied=rows.results.find(m=>m.mealType===mealType);if(occupied)return c.json({answer:`${mealType[0]!.toUpperCase()+mealType.slice(1)} on ${mealDate} already has “${occupied.title}” planned. Do you want to replace it with “${title}”?`,followUps:[`Replace ${occupied.title} with ${title} for ${mealType} on ${mealDate}`,"Keep the existing meal","Show me that day's meal plan"],generatedAt:new Date().toISOString(),requiresConfirmation:false,source:"kit-hub"});if(!(await canManage(c,a.householdId,a.user.id)))return c.json({answer:`“${title}” isn't planned yet, but you don't currently have permission to change the household meal plan.`,followUps:["Show me the meal plan"],generatedAt:new Date().toISOString(),requiresConfirmation:false,source:"kit-hub"});const p=await makeProposal(c,a,mealDate,mealType,title);const events=await c.env.DB.prepare("SELECT title,starts_at startsAt FROM everyday_events WHERE household_id=? AND starts_at>=? AND starts_at<? ORDER BY starts_at").bind(a.householdId,`${mealDate}T00:00:00.000Z`,`${mealDate}T23:59:59.999Z`).all<{title:string;startsAt:string}>();const recipe=await c.env.DB.prepare("SELECT name FROM meal_recipes WHERE household_id=? AND lower(name)=lower(?) LIMIT 1").bind(a.householdId,title).first<{name:string}>();const notes:string[]=[];if(events.results.length)notes.push(`I also found ${events.results.length} calendar item${events.results.length===1?"":"s"} that day.`);if(recipe)notes.push(`A saved recipe for “${recipe.name}” is available, so I can check its ingredients against Groceries afterwards.`);return c.json({answer:`I checked the meal plan first. Nothing matching “${title}” is planned for ${mealDate}, so I can add it as ${mealType} after you approve the change below.${notes.length?` ${notes.join(" ")}`:""}`,proposal:p,followUps:[...(events.results.length?["Check schedule conflicts that day"]:[]),...(recipe?[`Check missing ingredients for ${recipe.name}`]:[]),"Show me that day's meal plan"],generatedAt:new Date().toISOString(),requiresConfirmation:true,source:"kit-hub"})}

app.post("/api/v1/households/:householdId/silvi/ask",async(c,next)=>{const body=await c.req.json().catch(()=>null) as {question?:unknown}|null,question=clean(body?.question,700);const a=await access(c);if("response" in a)return a.response;const tz=await timeZone(c,a.householdId,a.user.id);const memory=await c.env.DB.prepare("SELECT kind,payload_json payloadJson,expires_at expiresAt FROM silvi_clarification_state WHERE household_id=? AND user_id=?").bind(a.householdId,a.user.id).first<{kind:string;payloadJson:string;expiresAt:string}>();if(memory&&Date.parse(memory.expiresAt)<=Date.now())await clearMemory(c,a.householdId,a.user.id);
if(memory?.kind==="meal.type"&&Date.parse(memory.expiresAt)>Date.now()&&question.length<=30){const mealType=/^(breakfast|lunch|dinner|snack)$/i.test(question.trim())?question.trim().toLowerCase():"";if(mealType){const saved=JSON.parse(memory.payloadJson) as {title?:unknown;hasDate?:unknown;offset?:unknown;weekday?:unknown};const title=clean(saved.title,120);await clearMemory(c,a.householdId,a.user.id);if(!title)return next();if(!Boolean(saved.hasDate)){await remember(c,a.householdId,a.user.id,"meal.date",{title,mealType});return c.json({answer:`Great — ${mealType}. When should I plan “${title}”?`,followUps:["Tonight","Tomorrow","Friday"],generatedAt:new Date().toISOString(),requiresConfirmation:false,source:"kit-hub"})}let offset=Number(saved.offset??0);const weekday=clean(saved.weekday,20);if(weekday){const d=weekdayOffset(weekday,tz);if(d!==null)offset=d}return planReply(c,a,localYmd(offset,tz),mealType,title)}}
if(memory?.kind==="meal.date"&&Date.parse(memory.expiresAt)>Date.now()&&question.length<=40){const saved=JSON.parse(memory.payloadJson) as {title?:unknown;mealType?:unknown};const title=clean(saved.title,120),mealType=["breakfast","lunch","dinner","snack"].includes(String(saved.mealType))?String(saved.mealType):"dinner",trimmed=question.trim();const offset=/^tomorrow$/i.test(trimmed)?1:/^(today|tonight)$/i.test(trimmed)?0:weekdayOffset(trimmed,tz);if(title&&offset!==null){await clearMemory(c,a.householdId,a.user.id);return planReply(c,a,localYmd(offset,tz),mealType,title)}}
const parsed=parseMeal(question);if(!parsed)return next();if(!parsed.explicitMealType){await remember(c,a.householdId,a.user.id,"meal.type",{title:parsed.title,hasDate:parsed.hasDate,offset:parsed.offset,weekday:parsed.weekday});return c.json({answer:`Should I plan “${parsed.title}” for breakfast, lunch, dinner, or a snack? You can reply with just the meal type.`,followUps:["Breakfast","Lunch","Dinner","Snack"],generatedAt:new Date().toISOString(),requiresConfirmation:false,source:"kit-hub"})}if(!parsed.hasDate){await remember(c,a.householdId,a.user.id,"meal.date",{title:parsed.title,mealType:parsed.mealType});return c.json({answer:`When should I plan “${parsed.title}” for ${parsed.mealType}? You can reply with “Tonight”, “Tomorrow”, or a weekday.`,followUps:["Tonight","Tomorrow","Friday"],generatedAt:new Date().toISOString(),requiresConfirmation:false,source:"kit-hub"})}let offset=parsed.offset;if(parsed.weekday){const d=weekdayOffset(parsed.weekday,tz);if(d!==null)offset=d}return planReply(c,a,localYmd(offset,tz),parsed.mealType,parsed.title)});
export default app;
