import { Hono } from "hono";
import { createAuth } from "./auth";
import { apiError, type AppBindings } from "./http";

const app = new Hono<AppBindings>();
type Ctx = Parameters<typeof apiError>[0];
type Priority = "attention" | "helpful" | "idea";
type Relevance = "personal" | "household";
type Step = { label: string; prompt: string; kind: "routine" | "task" | "meal" | "calendar"; benefit: string };
type Insight = { id:string; fingerprint:string; tone:"attention"|"balance"|"planning"; priority:Priority; relevance:Relevance; title:string; body:string; reason:string; why:string[]; steps:Step[] };
type Access = { householdId:string; user:{id:string;name?:string|null} };

async function access(c:Ctx):Promise<Access|{response:ReturnType<typeof apiError>}>{const session=await createAuth(c.env,c.req.raw).api.getSession({headers:c.req.raw.headers});if(!session?.user)return{response:apiError(c,401,"AUTH_REQUIRED","Sign in to open Silvi suggestions.")};const householdId=c.req.param("householdId")??"";const member=householdId?await c.env.DB.prepare("SELECT 1 FROM memberships WHERE household_id=? AND user_id=? AND status='active'").bind(householdId,session.user.id).first():null;if(!member)return{response:apiError(c,403,"HOUSEHOLD_VIEW_REQUIRED","You do not have access to this household.")};return{householdId,user:session.user}}
function hash(parts:unknown[]){const text=JSON.stringify(parts);let h=2166136261;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(36)}
async function preferenceMap(c:Ctx,a:Access){const rows=await c.env.DB.prepare("SELECT insight_id insightId,fingerprint,state,snoozed_until snoozedUntil FROM silvi_suggestion_preferences WHERE household_id=? AND user_id=?").bind(a.householdId,a.user.id).all<any>();return new Map(rows.results.map((r:any)=>[r.insightId,r]))}
function visible(insight:Insight,pref:any){if(!pref||pref.fingerprint!==insight.fingerprint)return true;if(pref.state==="dismissed")return false;if(pref.state==="snoozed"&&pref.snoozedUntil&&Date.parse(pref.snoozedUntil)>Date.now())return false;return true}
function dayKey(value:string){return String(value).slice(0,10)}
function overlap(a:any,b:any){const aStart=Date.parse(a.startsAt),aEnd=Date.parse(a.endsAt||a.startsAt),bStart=Date.parse(b.startsAt),bEnd=Date.parse(b.endsAt||b.startsAt);return Number.isFinite(aStart)&&Number.isFinite(bStart)&&Math.max(aStart,bStart)<Math.min(aEnd||aStart+3600000,bEnd||bStart+3600000)}

async function buildInsights(c:Ctx,a:Access){
 const now=new Date(),nowMs=now.getTime(),weekEnd=new Date(nowMs+7*86400000).toISOString(),today=now.toISOString().slice(0,10),monthAgo=new Date(nowMs-30*86400000).toISOString();
 const[members,tasks,routines,events,meals,completions]=await Promise.all([
  c.env.DB.prepare(`SELECT m.user_id userId,u.name FROM memberships m JOIN "user" u ON u.id=m.user_id WHERE m.household_id=? AND m.status='active' ORDER BY u.name`).bind(a.householdId).all<any>(),
  c.env.DB.prepare(`SELECT id,title,assignee_user_id assigneeUserId,due_at dueAt,priority,created_at createdAt FROM everyday_tasks WHERE household_id=? AND status='todo'`).bind(a.householdId).all<any>(),
  c.env.DB.prepare(`SELECT id,title,assignee_user_id assigneeUserId,next_due_at nextDueAt,cadence FROM household_routines WHERE household_id=? AND active=1`).bind(a.householdId).all<any>(),
  c.env.DB.prepare(`SELECT id,title,starts_at startsAt,ends_at endsAt,all_day allDay FROM everyday_events WHERE household_id=? AND starts_at>=? AND starts_at<=? ORDER BY starts_at`).bind(a.householdId,now.toISOString(),weekEnd).all<any>(),
  c.env.DB.prepare(`SELECT id,meal_date mealDate,meal_type mealType,title,cook_user_id cookUserId FROM meal_plans WHERE household_id=? AND meal_date>=? AND meal_date<=date(?, '+7 day')`).bind(a.householdId,today,today).all<any>(),
  c.env.DB.prepare(`SELECT completed_by completedBy,COUNT(*) count FROM household_routine_completions WHERE household_id=? AND completed_at>=? GROUP BY completed_by`).bind(a.householdId,monthAgo).all<any>(),
 ]);
 const insights:Insight[]=[];
 const completionMap=new Map(completions.results.map((x:any)=>[x.completedBy,Number(x.count)]));
 const workload=members.results.map((m:any)=>{const openTasks=tasks.results.filter((t:any)=>t.assigneeUserId===m.userId).length,openRoutines=routines.results.filter((r:any)=>r.assigneeUserId===m.userId).length,overdue=routines.results.filter((r:any)=>r.assigneeUserId===m.userId&&r.nextDueAt&&Date.parse(r.nextDueAt)<nowMs).length,completed30=completionMap.get(m.userId)??0;return{...m,open:openTasks+openRoutines,openTasks,openRoutines,overdue,completed30}});

 // Weekly household briefing: always low-noise, one compact overview.
 const dueSoon=tasks.results.filter((t:any)=>t.dueAt&&Date.parse(t.dueAt)>=nowMs&&Date.parse(t.dueAt)<=nowMs+7*86400000).length;
 const overdueTasks=tasks.results.filter((t:any)=>t.dueAt&&Date.parse(t.dueAt)<nowMs).length;
 const overdueRoutines=routines.results.filter((r:any)=>r.nextDueAt&&Date.parse(r.nextDueAt)<nowMs);
 const dinnerCount=meals.results.filter((m:any)=>m.mealType==="dinner").length;
 insights.push({id:"weekly-briefing",fingerprint:hash([today,dueSoon,overdueTasks,overdueRoutines.length,events.results.length,dinnerCount]),tone:"planning",priority:(overdueTasks+overdueRoutines.length)>2?"attention":"idea",relevance:"personal",title:"Your next 7 days at a glance",body:`${events.results.length} upcoming events, ${dueSoon} tasks due this week, ${overdueTasks+overdueRoutines.length} overdue items, and ${dinnerCount} dinners planned.`,reason:"Silvi combines the next week of Calendar, Tasks, Meals and Routines into one household briefing.",why:[`${events.results.length} Calendar events in the next 7 days`,`${dueSoon} Tasks due this week`,`${overdueTasks} overdue Tasks + ${overdueRoutines.length} overdue Routines`,`${dinnerCount} dinner plans`],steps:[{kind:"calendar",label:"Ask for my weekly plan",benefit:"Turns the overview into a practical day-by-day summary.",prompt:"Give me a concise day-by-day household briefing for the next 7 days. Call out overdue work, busy days, meals, and anything assigned to me. Do not change anything."}]});

 // Fairer chore balancing uses both current ownership and recent completed work.
 if(workload.length>=2){const sorted=[...workload].sort((x:any,y:any)=>(y.open+y.completed30*.35)-(x.open+x.completed30*.35)),most=sorted[0],least=sorted[sorted.length-1],gap=most.open-least.open,completionGap=most.completed30-least.completed30;if((most.open>=4&&gap>=3)||completionGap>=5){const candidateRoutine=routines.results.find((r:any)=>r.assigneeUserId===most.userId),candidateTask=tasks.results.find((t:any)=>t.assigneeUserId===most.userId),steps:Step[]=[];if(candidateRoutine)steps.push({kind:"routine",label:`Reassign ${candidateRoutine.title}`,benefit:`Moves one recurring responsibility away from ${most.name}.`,prompt:`Prepare a proposal to reassign the routine "${candidateRoutine.title}" from ${most.name} to ${least.name}.`});if(candidateTask)steps.push({kind:"task",label:`Reassign ${candidateTask.title}`,benefit:`Reduces ${most.name}'s current open assignment count by one.`,prompt:`Prepare a proposal to reassign the task "${candidateTask.title}" from ${most.name} to ${least.name}.`});const personal=most.userId===a.user.id||least.userId===a.user.id;insights.push({id:"workload-balance",fingerprint:hash([most.userId,most.open,most.completed30,least.userId,least.open,least.completed30,candidateRoutine?.id,candidateTask?.id]),tone:"balance",priority:gap>=5||completionGap>=8?"attention":"helpful",relevance:personal?"personal":"household",title:personal&&most.userId===a.user.id?"Your household load is heavier right now":`${most.name} has been carrying more household work`,body:`${most.name} has ${most.open} open assignments and completed ${most.completed30} routines in the last 30 days; ${least.name} has ${least.open} open and completed ${least.completed30}.`,reason:"Silvi now considers both current assignments and recent routine completions, not just who has the longest list today.",why:[`${most.name}: ${most.open} open, ${most.completed30} routine completions in 30 days`,`${least.name}: ${least.open} open, ${least.completed30} completions`,"This is a coordination signal, not a score of effort or contribution."],steps:steps.slice(0,2)})}}

 // Schedule conflict detection for overlapping household events.
 const conflicts:Array<[any,any]>=[];for(let i=0;i<events.results.length;i++)for(let j=i+1;j<events.results.length;j++){const x=events.results[i],y=events.results[j];if(!x.allDay&&!y.allDay&&dayKey(x.startsAt)===dayKey(y.startsAt)&&overlap(x,y))conflicts.push([x,y])}
 if(conflicts.length){const[x,y]=conflicts[0],date=dayKey(x.startsAt);insights.push({id:`schedule-conflict-${date}`,fingerprint:hash(conflicts.slice(0,4).map(([p,q])=>[p.id,p.startsAt,p.endsAt,q.id,q.startsAt,q.endsAt])),tone:"attention",priority:"attention",relevance:"household",title:`Calendar overlap on ${date}`,body:`“${x.title}” overlaps with “${y.title}”. There ${conflicts.length===1?"is":"are"} ${conflicts.length} overlapping event pair${conflicts.length===1?"":"s"} this week.`,reason:"Silvi compares timed Calendar events and flags actual overlaps, while ignoring all-day entries.",why:[`${x.title}: ${new Date(x.startsAt).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}–${new Date(x.endsAt||x.startsAt).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}`,`${y.title}: ${new Date(y.startsAt).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}–${new Date(y.endsAt||y.startsAt).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}`],steps:[{kind:"calendar",label:"Review the overlap",benefit:"Lets Silvi suggest a safer time without changing either event automatically.",prompt:`Review the Calendar overlap between "${x.title}" and "${y.title}" on ${date}. Suggest the least disruptive option and prepare one Calendar change proposal only if a clear move makes sense.`}]})}

 // Forgotten tasks: overdue by 2+ days or old undated tasks untouched for 14+ days.
 const forgotten=tasks.results.filter((t:any)=>t.dueAt?Date.parse(t.dueAt)<nowMs-2*86400000:Date.parse(t.createdAt)<nowMs-14*86400000);
 const myForgotten=forgotten.filter((t:any)=>t.assigneeUserId===a.user.id);
 if(forgotten.length){const first=myForgotten[0]??forgotten[0];insights.push({id:"forgotten-tasks",fingerprint:hash(forgotten.slice(0,8).map((t:any)=>[t.id,t.dueAt,t.assigneeUserId])),tone:"attention",priority:myForgotten.length?"attention":"helpful",relevance:myForgotten.length?"personal":"household",title:myForgotten.length?`${myForgotten.length} of your tasks may have slipped through`:`${forgotten.length} older tasks may need a decision`,body:"These tasks are either several days overdue or have been sitting without a due date for more than two weeks.",reason:"Silvi avoids calling a task forgotten immediately; it waits for a meaningful age or overdue threshold.",why:[`${forgotten.filter((t:any)=>t.dueAt).length} are more than 2 days overdue`,`${forgotten.filter((t:any)=>!t.dueAt).length} have no due date and are over 14 days old`],steps:[{kind:"task",label:`Review ${first.title}`,benefit:"Decide whether to finish, reschedule, reassign or remove ambiguity around this task.",prompt:`Review the older task "${first.title}". Based on its current due date, assignment and household workload, suggest the best next step and prepare at most one task proposal for me to review.`}]})}

 // Meal/calendar coordination: find busiest evening and missing dinner or an existing plan to simplify.
 const eventsByDate=new Map<string,any[]>();for(const e of events.results){const key=dayKey(e.startsAt),list=eventsByDate.get(key)??[];list.push(e);eventsByDate.set(key,list)}
 let busiest:{date:string;events:any[]}|null=null;for(const[date,dayEvents]of eventsByDate){const evening=dayEvents.filter((e:any)=>{const h=new Date(e.startsAt).getHours();return h>=15&&h<=21});if(evening.length>=2&&(!busiest||evening.length>busiest.events.length))busiest={date,events:evening}}
 if(busiest){const dinner=meals.results.find((m:any)=>m.mealDate===busiest!.date&&m.mealType==="dinner"),steps:Step[]=dinner?[{kind:"meal",label:`Simplify ${dinner.title}`,benefit:"Keeps dinner effort aligned with a crowded evening.",prompt:`It is a busy evening on ${busiest.date} with ${busiest.events.length} events. Suggest a simpler dinner than "${dinner.title}" and prepare a meal proposal for ${busiest.date} dinner. Do not change anything until I approve.`}]:[{kind:"meal",label:"Plan an easy dinner",benefit:"Removes one decision from an already busy evening.",prompt:`It is a busy evening on ${busiest.date} with ${busiest.events.length} events and no dinner planned. Prepare a simple practical dinner proposal for that evening. Do not change anything until I approve.`}];insights.push({id:`busy-evening-${busiest.date}`,fingerprint:hash([busiest.date,busiest.events.map((e:any)=>e.id),dinner?.id]),tone:"planning",priority:busiest.events.length>=3?"attention":"helpful",relevance:"household",title:`Meal planning could help on ${busiest.date}`,body:`There are ${busiest.events.length} afternoon/evening events${dinner?` and “${dinner.title}” is planned for dinner`:" and no dinner is planned yet"}.`,reason:"Silvi coordinates Calendar pressure with Meals so busy evenings require fewer last-minute decisions.",why:[`${busiest.events.length} events between 15:00 and 21:00`,dinner?`Dinner currently planned: ${dinner.title}`:"No dinner currently planned"],steps})}

 const unassignedUrgent=tasks.results.filter((t:any)=>!t.assigneeUserId&&(t.priority==="high"||(t.dueAt&&Date.parse(t.dueAt)-nowMs<86400000)));if(unassignedUrgent.length>=2)insights.push({id:"unassigned-urgent",fingerprint:hash(unassignedUrgent.map((t:any)=>[t.id,t.dueAt,t.priority])),tone:"planning",priority:"helpful",relevance:"household",title:`${unassignedUrgent.length} important tasks have no owner`,body:"A few time-sensitive tasks are still unassigned, which can make them easier to miss.",reason:"Silvi looks for high-priority or soon-due Tasks that do not have an assignee.",why:[`${unassignedUrgent.length} unassigned important tasks`],steps:unassignedUrgent.slice(0,2).map((t:any)=>({kind:"task" as const,label:`Assign ${t.title}`,benefit:"Makes responsibility explicit before the task is due.",prompt:`Review the unassigned task "${t.title}" and household workload. Suggest the fairest assignee and prepare only that assignment proposal for me to approve.`}))});

 const pref=await preferenceMap(c,a),priorityRank:Record<Priority,number>={attention:0,helpful:1,idea:2},relevanceRank:Record<Relevance,number>={personal:0,household:1};const filtered=insights.filter(i=>visible(i,pref.get(i.id))).sort((x,y)=>relevanceRank[x.relevance]-relevanceRank[y.relevance]||priorityRank[x.priority]-priorityRank[y.priority]);return{generatedAt:new Date().toISOString(),briefing:insights.find(i=>i.id==="weekly-briefing")??null,insights:filtered.slice(0,5),workload};
}

app.get("/api/v1/households/:householdId/silvi/insights",async c=>{const a=await access(c);if("response" in a)return a.response;return c.json(await buildInsights(c,a))});
app.post("/api/v1/households/:householdId/silvi/insights/:insightId/preference",async c=>{const a=await access(c);if("response" in a)return a.response;const body=await c.req.json().catch(()=>null) as {action?:unknown;minutes?:unknown;fingerprint?:unknown}|null,action=body?.action,insightId=c.req.param("insightId"),fingerprint=typeof body?.fingerprint==="string"?body.fingerprint.slice(0,80):"";if(!fingerprint||(action!=="dismiss"&&action!=="snooze"&&action!=="clear"))return apiError(c,422,"VALIDATION_FAILED","Choose a valid suggestion preference.");if(action==="clear"){await c.env.DB.prepare("DELETE FROM silvi_suggestion_preferences WHERE household_id=? AND user_id=? AND insight_id=?").bind(a.householdId,a.user.id,insightId).run();return c.json({ok:true})}const minutes=action==="snooze"?([1440,10080].includes(Number(body?.minutes))?Number(body?.minutes):1440):null,until=minutes?new Date(Date.now()+minutes*60000).toISOString():null;await c.env.DB.prepare(`INSERT INTO silvi_suggestion_preferences(household_id,user_id,insight_id,fingerprint,state,snoozed_until,updated_at) VALUES(?,?,?,?,?,?,datetime('now')) ON CONFLICT(household_id,user_id,insight_id) DO UPDATE SET fingerprint=excluded.fingerprint,state=excluded.state,snoozed_until=excluded.snoozed_until,updated_at=datetime('now')`).bind(a.householdId,a.user.id,insightId,fingerprint,action==="dismiss"?"dismissed":"snoozed",until).run();return c.json({ok:true,snoozedUntil:until})});
export default app;
