import { Hono } from "hono";
import { createAuth } from "./auth";
import { apiError, type AppBindings } from "./http";

const app=new Hono<AppBindings>();
type Ctx=Parameters<typeof apiError>[0];
function clean(v:unknown,max=180){return typeof v==="string"?v.trim().slice(0,max):""}
async function session(c:Ctx){return(await createAuth(c.env,c.req.raw).api.getSession({headers:c.req.raw.headers}))?.user??null}
async function member(c:Ctx,h:string,u:string){return c.env.DB.prepare("SELECT role_key role FROM memberships WHERE household_id=? AND user_id=? AND status='active'").bind(h,u).first<{role:string}>()}
async function canManage(c:Ctx,h:string,u:string){const m=await member(c,h,u);if(!m)return false;const o=await c.env.DB.prepare("SELECT effect FROM member_permission_overrides WHERE household_id=? AND user_id=? AND permission_key='tasks.manage' LIMIT 1").bind(h,u).first<{effect:string}>();if(o)return o.effect==="allow";const p=await c.env.DB.prepare("SELECT effect FROM role_permissions WHERE role_key=? AND permission_key='tasks.manage' LIMIT 1").bind(m.role).first<{effect:string}>();return p?.effect==="allow"}
async function clear(c:Ctx,h:string,u:string){await c.env.DB.prepare("DELETE FROM silvi_clarification_state WHERE household_id=? AND user_id=?").bind(h,u).run()}
async function remember(c:Ctx,h:string,u:string,payload:Record<string,unknown>){await c.env.DB.prepare("INSERT INTO silvi_clarification_state(household_id,user_id,kind,payload_json,expires_at) VALUES(?,?,?,?,?) ON CONFLICT(household_id,user_id) DO UPDATE SET kind=excluded.kind,payload_json=excluded.payload_json,expires_at=excluded.expires_at,created_at=datetime('now')").bind(h,u,"task.assignee",JSON.stringify(payload),new Date(Date.now()+10*60000).toISOString()).run()}
app.post("/api/v1/households/:householdId/silvi/ask",async(c,next)=>{const user=await session(c);if(!user)return next();const h=c.req.param("householdId")??"";if(!h||!(await member(c,h,user.id)))return next();const body=await c.req.json().catch(()=>null) as {question?:unknown}|null,q=clean(body?.question,700);const memory=await c.env.DB.prepare("SELECT kind,payload_json payloadJson,expires_at expiresAt FROM silvi_clarification_state WHERE household_id=? AND user_id=?").bind(h,user.id).first<{kind:string;payloadJson:string;expiresAt:string}>();if(memory?.kind==="task.assignee"&&Date.parse(memory.expiresAt)>Date.now()&&q.length<=60){const saved=JSON.parse(memory.payloadJson) as {taskId?:unknown;title?:unknown};const taskId=clean(saved.taskId,120),title=clean(saved.title,160);const people=await c.env.DB.prepare(`SELECT m.user_id userId,u.name FROM memberships m JOIN "user" u ON u.id=m.user_id WHERE m.household_id=? AND m.status='active'`).bind(h).all<{userId:string;name:string}>();const wanted=q.toLowerCase().replace(/^(?:assign (?:it )?to|to)\s+/i,"").trim(),matches=people.results.filter(p=>p.name.toLowerCase()===wanted||p.name.toLowerCase().startsWith(wanted)||wanted.startsWith(p.name.toLowerCase()));if(matches.length===1&&taskId){await clear(c,h,user.id);if(!(await canManage(c,h,user.id)))return c.json({answer:"You don't currently have permission to assign household tasks.",requiresConfirmation:false,generatedAt:new Date().toISOString(),source:"kit-hub"});const chosen=matches[0]!,id=crypto.randomUUID(),expiresAt=new Date(Date.now()+10*60000).toISOString(),payload={taskId,assigneeUserId:chosen.userId},summary=`Assign task “${title||"task"}” to ${chosen.name}.`;await c.env.DB.prepare("INSERT INTO silvi_action_proposals(id,household_id,user_id,action_type,summary,payload_json,expires_at) VALUES(?,?,?,?,?,?,?)").bind(id,h,user.id,"task.update",summary,JSON.stringify(payload),expiresAt).run();return c.json({answer:`Got it. I can assign “${title}” to ${chosen.name} after you approve the change below.`,proposal:{id,type:"task.update",summary,payload,expiresAt},requiresConfirmation:true,generatedAt:new Date().toISOString(),source:"kit-hub"})}if(matches.length>1)return c.json({answer:"I found more than one household member with a similar name. Which one do you mean?",followUps:matches.slice(0,4).map(p=>p.name),requiresConfirmation:false,generatedAt:new Date().toISOString(),source:"kit-hub"})}
const match=q.match(/^(?:assign|give)\s+(?:the\s+)?(?:task\s+)?(.+?)(?:\s+to\s+who)?[?!.]?$/i);if(!match||/\s+to\s+[A-Za-z]/i.test(q))return next();const wanted=clean(match[1],160),tasks=await c.env.DB.prepare("SELECT id,title FROM everyday_tasks WHERE household_id=? AND status='todo' ORDER BY created_at DESC").bind(h).all<{id:string;title:string}>();const candidates=tasks.results.filter(t=>t.title.toLowerCase().includes(wanted.toLowerCase())||wanted.toLowerCase().includes(t.title.toLowerCase()));if(candidates.length===1){const task=candidates[0]!;await remember(c,h,user.id,{taskId:task.id,title:task.title});const people=await c.env.DB.prepare(`SELECT u.name FROM memberships m JOIN "user" u ON u.id=m.user_id WHERE m.household_id=? AND m.status='active' ORDER BY u.name`).bind(h).all<{name:string}>();return c.json({answer:`Who should I assign “${task.title}” to? You can reply with just their name.`,followUps:people.results.slice(0,5).map(p=>p.name),requiresConfirmation:false,generatedAt:new Date().toISOString(),source:"kit-hub"})}if(candidates.length>1)return c.json({answer:"I found several open tasks that could match. Which task do you mean?",followUps:candidates.slice(0,4).map(t=>`Assign ${t.title}`),requiresConfirmation:false,generatedAt:new Date().toISOString(),source:"kit-hub"});return next()});
export default app;
